#!/bin/bash
# ============================================================
# OpenIDX Claude Code Runner (Direct — No Container)
# ============================================================
# Usage: ./run-claude.sh "task description" [branch-name] [model]
#
# Called by n8n Execute Command node.
# Requires: claude (installed), git, gh (optional for PR creation)
# ============================================================

set -euo pipefail

TASK="$1"
BRANCH="${2:-claude/auto-$(date +%s)}"
MODEL="${3:-glm-4.7}"
REPO_DIR="${OPENIDX_REPO:-$HOME/openidx}"

# ---- Validation ----
if [ -z "$TASK" ]; then
    echo '{"status":"error","error":"No task provided"}'
    exit 1
fi

if [ ! -d "$REPO_DIR/.git" ]; then
    echo "{\"status\":\"error\",\"error\":\"Repo not found at $REPO_DIR\"}"
    exit 1
fi

# ---- Prepare repo ----
cd "$REPO_DIR"
git fetch origin 2>/dev/null || true
git checkout dev 2>/dev/null || git checkout main 2>/dev/null
git pull 2>/dev/null || true

# Create feature branch
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH" 2>/dev/null

# ---- Run Claude Code ----
OUTPUT=$(ANTHROPIC_MODEL="$MODEL" claude --print -p "$TASK" 2>&1) || true
EXIT_CODE=$?

# ---- Check for changes ----
CHANGES=$(git status --porcelain)
PR_URL="none"

if [ -n "$CHANGES" ]; then
    git add -A
    COMMIT_MSG=$(echo "$TASK" | head -c 72)
    git commit -m "feat: $COMMIT_MSG" -m "Automated by Claude Code via n8n" 2>/dev/null || true
    git push origin "$BRANCH" 2>/dev/null || git push --set-upstream origin "$BRANCH" 2>/dev/null

    # Create PR if gh CLI is available
    if command -v gh &> /dev/null; then
        PR_URL=$(gh pr create \
            --base dev \
            --head "$BRANCH" \
            --title "🤖 $COMMIT_MSG" \
            --body "## Automated Task

**Task:** $TASK
**Model:** $MODEL
**Branch:** $BRANCH

### Claude Code Output
\`\`\`
$(echo "$OUTPUT" | tail -100)
\`\`\`

---
*Generated by Claude Code via n8n automation*" 2>&1) || PR_URL="pr-creation-failed"
    fi
fi

# ---- Return to dev ----
git checkout dev 2>/dev/null || true

# ---- Output JSON result ----
# Escape output for JSON
SAFE_OUTPUT=$(echo "$OUTPUT" | head -80 | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))" 2>/dev/null || echo '""')

cat << RESULT
{
    "status": "$([ $EXIT_CODE -eq 0 ] && echo 'success' || echo 'failed')",
    "exit_code": $EXIT_CODE,
    "branch": "$BRANCH",
    "changes": "$([ -n "$CHANGES" ] && echo 'yes' || echo 'no')",
    "pr_url": "$PR_URL",
    "model": "$MODEL",
    "output_preview": $SAFE_OUTPUT
}
RESULT
