-- Rollback 001: Initial Schema

DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS composite_roles CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS group_memberships CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS users CASCADE;
