//go:build !embed_migrations

package migrations

// LoadMigrations loads all migrations from the embedded filesystem
func (m *Migrator) LoadMigrations() ([]*Migration, error) {
	// For embedded migrations, use predefined list
	return allMigrations(), nil
}

// allMigrations returns the complete list of migrations
// This is generated from the migrations directory
func allMigrations() []*Migration {
	return []*Migration{
		{
			Version:     1,
			Name:        "initial_schema",
			Description: "Initial database schema with core tables",
			UpSQL:       initialSchemaUp,
			DownSQL:     initialSchemaDown,
		},
		{
			Version:     2,
			Name:        "oauth_oidc",
			Description: "OAuth 2.0 / OIDC tables",
			UpSQL:       oauthOIDCUp,
			DownSQL:     oauthOIDCDown,
		},
		{
			Version:     3,
			Name:        "scim",
			Description: "SCIM 2.0 provisioning tables",
			UpSQL:       scimUp,
			DownSQL:     scimDown,
		},
		{
			Version:     4,
			Name:        "governance",
			Description: "Governance tables for access reviews and policies",
			UpSQL:       governanceUp,
			DownSQL:     governanceDown,
		},
		{
			Version:     5,
			Name:        "mfa",
			Description: "Multi-factor authentication tables (TOTP, WebAuthn, Push)",
			UpSQL:       mfaUp,
			DownSQL:     mfaDown,
		},
		{
			Version:     6,
			Name:        "sessions",
			Description: "Session management tables",
			UpSQL:       sessionsUp,
			DownSQL:     sessionsDown,
		},
		{
			Version:     7,
			Name:        "applications",
			Description: "Application management tables",
			UpSQL:       applicationsUp,
			DownSQL:     applicationsDown,
		},
		{
			Version:     8,
			Name:        "audit_compliance",
			Description: "Audit and compliance tables",
			UpSQL:       auditComplianceUp,
			DownSQL:     auditComplianceDown,
		},
		{
			Version:     9,
			Name:        "indexes",
			Description: "Performance indexes",
			UpSQL:       indexesUp,
			DownSQL:     indexesDown,
		},
		{
			Version:     10,
			Name:        "seed_data",
			Description: "Initial seed data (admin user, roles, groups)",
			UpSQL:       seedDataUp,
			DownSQL:     seedDataDown,
		},
		{
			Version:     11,
			Name:        "identity_providers",
			Description: "External identity provider integration (OIDC/SAML)",
			UpSQL:       identityProvidersUp,
			DownSQL:     identityProvidersDown,
		},
		{
			Version:     12,
			Name:        "provisioning_rules",
			Description: "Provisioning rules and password reset tokens",
			UpSQL:       provisioningRulesUp,
			DownSQL:     provisioningRulesDown,
		},
		{
			Version:     13,
			Name:        "permissions",
			Description: "Permissions and role permissions tables",
			UpSQL:       permissionsUp,
			DownSQL:     permissionsDown,
		},
		{
			Version:     14,
			Name:        "system_settings",
			Description: "System settings and configuration",
			UpSQL:       systemSettingsUp,
			DownSQL:     systemSettingsDown,
		},
		{
			Version:     15,
			Name:        "directory_integrations",
			Description: "Directory integration tables",
			UpSQL:       directoryIntegrationsUp,
			DownSQL:     directoryIntegrationsDown,
		},
		{
			Version:     16,
			Name:        "proxy_routes",
			Description: "Zero Trust Access Proxy routes and sessions",
			UpSQL:       proxyRoutesUp,
			DownSQL:     proxyRoutesDown,
		},
		{
			Version:     17,
			Name:        "openziti",
			Description: "OpenZiti integration tables",
			UpSQL:       openzitiUp,
			DownSQL:     openzitiDown,
		},
		{
			Version:     18,
			Name:        "directory_sync",
			Description: "Directory sync state and logs",
			UpSQL:       directorySyncUp,
			DownSQL:     directorySyncDown,
		},
		{
			Version:     19,
			Name:        "conditional_access",
			Description: "Conditional access and risk engine tables",
			UpSQL:       conditionalAccessUp,
			DownSQL:     conditionalAccessDown,
		},
		{
			Version:     20,
			Name:        "api_keys_webhooks",
			Description: "API keys, webhooks, email verification, invitations",
			UpSQL:       apiKeysWebhooksUp,
			DownSQL:     apiKeysWebhooksDown,
		},
		{
			Version:     21,
			Name:        "access_requests",
			Description: "Access request and approval workflow tables",
			UpSQL:       accessRequestsUp,
			DownSQL:     accessRequestsDown,
		},
		{
			Version:     22,
			Name:        "security_alerts",
			Description: "Security alerts and anomaly detection",
			UpSQL:       securityAlertsUp,
			DownSQL:     securityAlertsDown,
		},
		{
			Version:     23,
			Name:        "password_management",
			Description: "Password history and credential rotation",
			UpSQL:       passwordManagementUp,
			DownSQL:     passwordManagementDown,
		},
		{
			Version:     24,
			Name:        "session_enhancements",
			Description: "Session management enhancements",
			UpSQL:       sessionEnhancementsUp,
			DownSQL:     sessionEnhancementsDown,
		},
		{
			Version:     25,
			Name:        "multitenancy",
			Description: "Multi-tenancy support with organizations",
			UpSQL:       multitenancyUp,
			DownSQL:     multitenancyDown,
		},
		{
			Version:     26,
			Name:        "reporting",
			Description: "Advanced reporting tables",
			UpSQL:       reportingUp,
			DownSQL:     reportingDown,
		},
		{
			Version:     27,
			Name:        "self_service",
			Description: "Self-service portal tables",
			UpSQL:       selfServiceUp,
			DownSQL:     selfServiceDown,
		},
		{
			Version:     28,
			Name:        "notifications",
			Description: "Notification system tables",
			UpSQL:       notificationsUp,
			DownSQL:     notificationsDown,
		},
		{
			Version:     29,
			Name:        "ziti_enhanced",
			Description: "OpenZiti enhanced features (posture checks, policy sync)",
			UpSQL:       zitiEnhancedUp,
			DownSQL:     zitiEnhancedDown,
		},
		{
			Version:     30,
			Name:        "user_roles_expires_at",
			Description: "Time-bound role assignments: adds the expires_at column already referenced by GenerateJWT and the role-expiry cleaner",
			UpSQL:       userRolesExpiresAtUp,
			DownSQL:     userRolesExpiresAtDown,
		},
		{
			Version:     31,
			Name:        "oauth_refresh_tokens_session_id",
			Description: "Adds the session_id column oauth_refresh_tokens has been silently failing INSERTs on since session-bound rotation landed; fixes the refresh-token grant",
			UpSQL:       oauthRefreshSessionIDUp,
			DownSQL:     oauthRefreshSessionIDDown,
		},
		{
			Version:     32,
			Name:        "privacy_tables",
			Description: "Brings privacy/GDPR tables (user_consents, data_subject_requests, privacy_retention_policies, privacy_assessments) under the migration runner — previously only created by deployments/docker/init-db.sql, so Helm/Terraform installs were missing them",
			UpSQL:       privacyTablesUp,
			DownSQL:     privacyTablesDown,
		},
		{
			Version:     33,
			Name:        "qr_login_sessions",
			Description: "Adds the qr_login_sessions table that internal/identity/passwordless.go has been INSERTing into since the QR-login feature shipped, but which no migration ever created — /oauth/qr-login/create was 500ing for every install on the first INSERT. Surfaced by the PR #126 integration tests.",
			UpSQL:       qrLoginSessionsUp,
			DownSQL:     qrLoginSessionsDown,
		},
		{
			Version:     34,
			Name:        "org_id_columns",
			Description: "Adds NULL-able org_id UUID columns + idx_<table>_org_id indexes to ~55 tables the v2.0 multi-tenancy design says must be org-scoped but that migration v025 didn't reach. Idempotent (IF NOT EXISTS). No backfill, no NOT NULL, no FK — those land in v035 and v036. Tables that are genuinely install-wide (organizations, permissions, system_settings, ip_threat_list, posture_check_types, policy_sync_state) are deliberately not scoped.",
			UpSQL:       orgIDColumnsUp,
			DownSQL:     orgIDColumnsDown,
		},
		{
			Version:     35,
			Name:        "org_id_backfill",
			Description: "Backfills the default organization UUID (00000000-0000-0000-0000-000000000010, created by v025) into every NULL org_id row across the ~55 tables v34 scoped. Idempotent (WHERE org_id IS NULL guards each UPDATE). Defensive INSERT at the top ensures the default org row exists even on installs that somehow skipped v25. No schema change, no constraint change, no behavioral change. Sets up v036 to add NOT NULL + FK.",
			UpSQL:       orgIDBackfillUp,
			DownSQL:     orgIDBackfillDown,
		},
		{
			Version:     36,
			Name:        "org_id_constraints",
			Description: "Final v1.6.0 foundation migration. For each of the 68 scoped tables: SET DEFAULT to default org UUID (preserves v1.6.0 ship gate — INSERTs that omit org_id silently land in default org), SET NOT NULL (schema correctness; v35 backfilled every row so this never rewrites data), ADD FK to organizations(id) ON DELETE RESTRICT (referential integrity), CREATE permissive RLS policy (placeholder — v1.8.0 ALTER POLICY tightens to a real org_id filter and ALTER TABLE ENABLE ROW LEVEL SECURITY activates enforcement). RLS itself is NOT enabled here; v1.8.0 owns activation.",
			UpSQL:       orgIDConstraintsUp,
			DownSQL:     orgIDConstraintsDown,
		},
		{
			Version:     37,
			Name:        "rls_activate",
			Description: "v1.8.0 RLS belt. Rewrites the 68 dormant pol_<t>_org_scope policies from USING(true) to a real tenant predicate — app.bypass_rls='on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid (fail-closed when the GUC is unset) — then ENABLE + FORCE ROW LEVEL SECURITY per table (FORCE because the app connects as the table owner). The per-request GUC is set at pool checkout from orgctx (internal/common/database); background/cross-org jobs opt into app.bypass_rls via orgctx.WithBypassRLS. Down reverts to USING(true) + RLS off.",
			UpSQL:       rlsActivateUp,
			DownSQL:     rlsActivateDown,
		},
		{
			Version:     38,
			Name:        "tenant_tables",
			Description: "Create tenant_branding, tenant_domains and tenant_settings in the versioned migration set. These back the multi-tenant login (per-org branding read by the public branding endpoint + OAuth login page) and domain-based tenant resolution. They previously lived only in deployments/docker/init-db.sql (docker-compose only), so managed-RDS/Helm deploys never had them. DDL is idempotent (IF NOT EXISTS) — a no-op on init-db.sql-bootstrapped clusters. Not placed under the RLS belt: both are read before any org context exists.",
			UpSQL:       tenantTablesUp,
			DownSQL:     tenantTablesDown,
		},
		{
			Version:     39,
			Name:        "device_trust_risk_tables",
			Description: "Create device_trust_requests, device_trust_settings, trusted_browsers and risk_policies in the versioned migration set. Their internal/identity handlers returned 500 on managed-RDS/Helm/migrate deploys because the tables existed only in deployments/docker/init-db.sql (same gap class as v38's tenant_* tables). DDL is idempotent. A wider init-db.sql↔migrations gap (~70 more tables) is tracked as separate follow-up.",
			UpSQL:       deviceTrustRiskUp,
			DownSQL:     deviceTrustRiskDown,
		},
		{
			Version:     40,
			Name:        "access_schema_reconcile",
			Description: "Fix the access-service App Publish feature on managed-RDS/Helm/migrate deploys: create published_apps, discovered_paths, service_features (init-db.sql-only tables, so /api/v1/access/apps 500'd) and add the ~12 proxy_routes columns the access code SELECTs (idp_id, route_type, remote_host/port, posture/risk/guacamole/browzer, …) that the migrations had drifted behind init-db.sql (so /api/v1/access/routes 500'd with 'column idp_id does not exist'). Idempotent.",
			UpSQL:       accessSchemaUp,
			DownSQL:     accessSchemaDown,
		},
		{
			Version:     41,
			Name:        "published_apps_public_host",
			Description: "Adds public_host + landing_path to published_apps for the one-click 'open internal app' publish flow (POST /api/v1/access/apps/:id/publish-app): public_host records the external host assigned to an app (UI display + idempotent re-publish); landing_path is where the launcher tile points for apps whose UI is not at the site root (default '/'). Idempotent (ADD COLUMN IF NOT EXISTS).",
			UpSQL:       oneClickAppsUp,
			DownSQL:     oneClickAppsDown,
		},
		{
			Version:     42,
			Name:        "reconcile_table_gap",
			Description: "Create init-db.sql-only / loose-SQL tables missing on managed-RDS/Helm/migrate installs (same class as v38–v40): abac_policies, certification_campaigns, ai_agents (init-db.sql), saml_sessions (010_add_saml_idp_tables.sql), remote_support_sessions (202605150004_remote_support.up.sql) — fixes 500s on the ABAC Policies / AI Agents / Certification Campaigns / Remote Support pages and the saml_sessions session-worker errors. Also adds certification_campaigns started_at/completed_at/total_items that the run code writes but no source created. Idempotent. (agents, recommendations, notification_digest_settings have no schema anywhere — genuinely unimplemented, tracked separately.)",
			UpSQL:       tableGapV42Up,
			DownSQL:     tableGapV42Down,
		},
		{
			Version:     43,
			Name:        "reconcile_agent_recommendation_digest_tables",
			Description: "Create the Agent Fleet / AI Recommendations / Notification Digest tables missing on managed-RDS/Helm/migrate installs (same init-db↔migrations gap as v38–v42): enrolled_agents (+ agent_posture_results, agent_enrollment_tokens) from the loose 2025*_enrolled_agents files; ai_recommendations + recommendation_history and the ai_agents children ai_agent_credentials/permissions/activity (v42 created ai_agents but not its children) from init-db.sql; notification_digests from init-db.sql. Fixes 500s on the Agent Fleet, AI Recommendations and Notification Center digest pages. Idempotent; verbatim DDL; not org-scoped (matches source + handlers).",
			UpSQL:       agentRecoDigestUp,
			DownSQL:     agentRecoDigestDown,
		},
		{
			Version:     44,
			Name:        "reconcile_kiosk_policy_tables",
			Description: "Final init-db↔migrations reconcile pass (after v38–v43): create kiosk_policies + kiosk_policy_assignments (loose file 202605150003) — fixes 500 on GET /api/v1/access/kiosk/policies — and policy_recommendations + compliance_gaps (loose file 017_add_genai_and_advanced_auth_tables) for the AI policy-suggestion / compliance-gap endpoints. Idempotent; verbatim DDL; not org-scoped (matches source + handlers).",
			UpSQL:       kioskPolicyV44Up,
			DownSQL:     kioskPolicyV44Down,
		},
		{
			Version:     45,
			Name:        "ziti_browzer_config",
			Description: "Create ziti_browzer_config (init-db.sql-only) so BrowZer bootstrap can persist its external-JWT-signer / auth-policy / dial-policy IDs + OIDC settings and GET /ziti/browzer/status reports configured state. Same init-db↔migrations gap as v42–v44. Idempotent.",
			UpSQL:       zitiBrowzerConfigUp,
			DownSQL:     zitiBrowzerConfigDown,
		},
		{
			Version:     46,
			Name:        "ziti_identities_group_attrs_synced_at",
			Description: "Add ziti_identities.group_attrs_synced_at (init-db.sql-only column) so the Ziti user-sync INSERT/resync works on migrated installs; its absence blocked BrowZer identity provisioning (externalId + auth-policy wiring). Same init-db↔migrations gap as v42–v45. Idempotent.",
			UpSQL:       zitiIdentitiesGroupSyncUp,
			DownSQL:     zitiIdentitiesGroupSyncDown,
		},
		{
			Version:     47,
			Name:        "proxy_routes_hosting_mode",
			Description: "Add proxy_routes.hosting_mode (identity|direct) for the Ziti reconciler; backfill browzer_enabled routes to 'direct', else 'identity'. Idempotent.",
			UpSQL:       hostingModeUp,
			DownSQL:     hostingModeDown,
		},
		{
			Version:     48,
			Name:        "proxy_routes_landing_path",
			Description: "Add proxy_routes.landing_path (default '/') — where a route's bare host should land; the BrowZer router emits a 302 to it when not '/'. Idempotent.",
			UpSQL:       landingPathUp,
			DownSQL:     landingPathDown,
		},
		{
			Version:     49,
			Name:        "applications_referential_integrity",
			Description: "Add applications.route_id (→proxy_routes) and applications.oauth_client_id (→oauth_clients), both ON DELETE CASCADE; backfill from the client_id string conventions so tiles/apps can't orphan. Idempotent, non-destructive.",
			UpSQL:       appReferentialIntegrityUp,
			DownSQL:     appReferentialIntegrityDown,
		},
		{
			Version:     50,
			Name:        "device_posture_results_upsert_key",
			Description: "Add UNIQUE INDEX device_posture_results(identity_id, check_id) so the agent→device posture bridge upserts one latest row per check. Idempotent.",
			UpSQL:       devicePostureUpsertKeyUp,
			DownSQL:     devicePostureUpsertKeyDown,
		},
		{
			Version:     51,
			Name:        "drop_zt_policies",
			Description: "Drop the dead ZTPolicy tables (zt_policies, zt_policy_versions). Never wired into any service; absent on real installs. Belt cleanup, idempotent (DROP ... IF EXISTS).",
			UpSQL:       ztPolicyDropUp,
			DownSQL:     ztPolicyDropDown,
		},
		{
			Version:     52,
			Name:        "reconcile_continuous_verify_columns",
			Description: "Add the init-db-only continuous-verify columns (proxy_sessions.last_verified_at/verification_failures/geo_country/geo_city/idp_id/device_trusted; user_sessions.device_trusted + index) so the continuous session verifier's query works on migrate-based installs. Idempotent; Down is a no-op.",
			UpSQL:       continuousVerifyColumnsUp,
			DownSQL:     continuousVerifyColumnsDown,
		},
		{
			Version:     53,
			Name:        "provision_openidx_app_role",
			Description: "Provision the openidx_app NOSUPERUSER NOBYPASSRLS runtime role with blanket DML grants + default privileges, so the v37 FORCE'd RLS policies enforce once the app cuts its DATABASE_URL over to it. Passwordless (set at deploy). Migrations/DDL stay on the owner. Idempotent.",
			UpSQL:       rlsAppRoleUp,
			DownSQL:     rlsAppRoleDown,
		},
		{
			Version:     54,
			Name:        "reconcile_initdb_table_gap",
			Description: "Create the 58 tables that existed only in deployments/docker/init-db.sql so managed-Postgres/RDS/Helm/migrate installs stop 500ing across MFA variants, SAML/social/federation, lifecycle, ISPM, audit archival, bulk-ops, biometric, passwordless, guacamole and ziti-fabric features (the broad init-db<->migrations reconcile after v38-v45's ~15). Verbatim DDL, idempotent (IF NOT EXISTS) so it is a no-op on docker-compose installs. Not under the v37 RLS belt (non-FORCE tables; openidx_app unaffected). TestInitDBParity now keeps this gap from recurring.",
			UpSQL:       reconcileTableGapUp,
			DownSQL:     reconcileTableGapDown,
		},
		{
			Version:     55,
			Name:        "lifecycle_policy_executions",
			Description: "Split the deprovisioning policy-run execution log out of the workflow lifecycle_executions table (a name collision: the workflow schema won, so deprovisioning's policy_id queries failed on every install). Creates lifecycle_policy_executions; init-db.sql's dead second block is renamed in lockstep and internal/admin/deprovisioning.go repointed. Idempotent; not under the v37 RLS belt.",
			UpSQL:       lifecyclePolicyExecUp,
			DownSQL:     lifecyclePolicyExecDown,
		},
		{
			Version:     56,
			Name:        "vault_store",
			Description: "PAM credential vault store (M1): vault_secrets, vault_secret_versions, vault_access_grants, vault_checkouts — org-scoped under the v37 FORCE-RLS belt. Envelope ciphertext lives only in vault_secret_versions. Rotation (credential_rotation_policies) is deferred to M1b. Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       vaultStoreUp,
			DownSQL:     vaultStoreDown,
		},
		{
			Version:     57,
			Name:        "credential_rotation",
			Description: "PAM rotation engine (M1b): adds credential_rotation_policies (one-per-secret connector + schedule) and reconciles the dead credential_rotations table into a run ledger (org_id, policy_id, secret_id, version_from/to, connector_type, trigger, error_message, started_at, completed_at; service_account_id NOT NULL dropped). Both tables placed under the v37 FORCE-RLS belt. Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       credentialRotationUp,
			DownSQL:     credentialRotationDown,
		},
		{
			Version:     58,
			Name:        "jit_approval_drift_fix",
			Description: "Create jit_grants and request_approval_chains — referenced by internal/governance (jit.go, jit_expiry.go, request.go) but never created by any migration or init-db.sql, so POST /api/v1/governance/requests and the JIT/escalation background workers 500 today. Columns match the code's exact SQL usage. Not under the v37 RLS belt (jit_grants isn't org-scoped in code; request_approval_chains is a child of access_requests reached via the RLS-scoped parent) — matches the v42-v55 reconcile precedent. Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       jitDriftFixUp,
			DownSQL:     jitDriftFixDown,
		},
	}
}
