//go:build !embed_migrations

package migrations

// LoadMigrations loads all migrations from the embedded filesystem
func (m *Migrator) LoadMigrations() ([]*Migration, error) {
	// For embedded migrations, use predefined list
	return allMigrations(), nil
}

// allMigrations returns the complete list of migrations
// This is generated from the migrations directory
func allMigrations() []*Migration {
	return []*Migration{
		{
			Version:     1,
			Name:        "initial_schema",
			Description: "Initial database schema with core tables",
			UpSQL:       initialSchemaUp,
			DownSQL:     initialSchemaDown,
		},
		{
			Version:     2,
			Name:        "oauth_oidc",
			Description: "OAuth 2.0 / OIDC tables",
			UpSQL:       oauthOIDCUp,
			DownSQL:     oauthOIDCDown,
		},
		{
			Version:     3,
			Name:        "scim",
			Description: "SCIM 2.0 provisioning tables",
			UpSQL:       scimUp,
			DownSQL:     scimDown,
		},
		{
			Version:     4,
			Name:        "governance",
			Description: "Governance tables for access reviews and policies",
			UpSQL:       governanceUp,
			DownSQL:     governanceDown,
		},
		{
			Version:     5,
			Name:        "mfa",
			Description: "Multi-factor authentication tables (TOTP, WebAuthn, Push)",
			UpSQL:       mfaUp,
			DownSQL:     mfaDown,
		},
		{
			Version:     6,
			Name:        "sessions",
			Description: "Session management tables",
			UpSQL:       sessionsUp,
			DownSQL:     sessionsDown,
		},
		{
			Version:     7,
			Name:        "applications",
			Description: "Application management tables",
			UpSQL:       applicationsUp,
			DownSQL:     applicationsDown,
		},
		{
			Version:     8,
			Name:        "audit_compliance",
			Description: "Audit and compliance tables",
			UpSQL:       auditComplianceUp,
			DownSQL:     auditComplianceDown,
		},
		{
			Version:     9,
			Name:        "indexes",
			Description: "Performance indexes",
			UpSQL:       indexesUp,
			DownSQL:     indexesDown,
		},
		{
			Version:     10,
			Name:        "seed_data",
			Description: "Initial seed data (admin user, roles, groups)",
			UpSQL:       seedDataUp,
			DownSQL:     seedDataDown,
		},
		{
			Version:     11,
			Name:        "identity_providers",
			Description: "External identity provider integration (OIDC/SAML)",
			UpSQL:       identityProvidersUp,
			DownSQL:     identityProvidersDown,
		},
		{
			Version:     12,
			Name:        "provisioning_rules",
			Description: "Provisioning rules and password reset tokens",
			UpSQL:       provisioningRulesUp,
			DownSQL:     provisioningRulesDown,
		},
		{
			Version:     13,
			Name:        "permissions",
			Description: "Permissions and role permissions tables",
			UpSQL:       permissionsUp,
			DownSQL:     permissionsDown,
		},
		{
			Version:     14,
			Name:        "system_settings",
			Description: "System settings and configuration",
			UpSQL:       systemSettingsUp,
			DownSQL:     systemSettingsDown,
		},
		{
			Version:     15,
			Name:        "directory_integrations",
			Description: "Directory integration tables",
			UpSQL:       directoryIntegrationsUp,
			DownSQL:     directoryIntegrationsDown,
		},
		{
			Version:     16,
			Name:        "proxy_routes",
			Description: "Zero Trust Access Proxy routes and sessions",
			UpSQL:       proxyRoutesUp,
			DownSQL:     proxyRoutesDown,
		},
		{
			Version:     17,
			Name:        "openziti",
			Description: "OpenZiti integration tables",
			UpSQL:       openzitiUp,
			DownSQL:     openzitiDown,
		},
		{
			Version:     18,
			Name:        "directory_sync",
			Description: "Directory sync state and logs",
			UpSQL:       directorySyncUp,
			DownSQL:     directorySyncDown,
		},
		{
			Version:     19,
			Name:        "conditional_access",
			Description: "Conditional access and risk engine tables",
			UpSQL:       conditionalAccessUp,
			DownSQL:     conditionalAccessDown,
		},
		{
			Version:     20,
			Name:        "api_keys_webhooks",
			Description: "API keys, webhooks, email verification, invitations",
			UpSQL:       apiKeysWebhooksUp,
			DownSQL:     apiKeysWebhooksDown,
		},
		{
			Version:     21,
			Name:        "access_requests",
			Description: "Access request and approval workflow tables",
			UpSQL:       accessRequestsUp,
			DownSQL:     accessRequestsDown,
		},
		{
			Version:     22,
			Name:        "security_alerts",
			Description: "Security alerts and anomaly detection",
			UpSQL:       securityAlertsUp,
			DownSQL:     securityAlertsDown,
		},
		{
			Version:     23,
			Name:        "password_management",
			Description: "Password history and credential rotation",
			UpSQL:       passwordManagementUp,
			DownSQL:     passwordManagementDown,
		},
		{
			Version:     24,
			Name:        "session_enhancements",
			Description: "Session management enhancements",
			UpSQL:       sessionEnhancementsUp,
			DownSQL:     sessionEnhancementsDown,
		},
		{
			Version:     25,
			Name:        "multitenancy",
			Description: "Multi-tenancy support with organizations",
			UpSQL:       multitenancyUp,
			DownSQL:     multitenancyDown,
		},
		{
			Version:     26,
			Name:        "reporting",
			Description: "Advanced reporting tables",
			UpSQL:       reportingUp,
			DownSQL:     reportingDown,
		},
		{
			Version:     27,
			Name:        "self_service",
			Description: "Self-service portal tables",
			UpSQL:       selfServiceUp,
			DownSQL:     selfServiceDown,
		},
		{
			Version:     28,
			Name:        "notifications",
			Description: "Notification system tables",
			UpSQL:       notificationsUp,
			DownSQL:     notificationsDown,
		},
		{
			Version:     29,
			Name:        "ziti_enhanced",
			Description: "OpenZiti enhanced features (posture checks, policy sync)",
			UpSQL:       zitiEnhancedUp,
			DownSQL:     zitiEnhancedDown,
		},
		{
			Version:     30,
			Name:        "user_roles_expires_at",
			Description: "Time-bound role assignments: adds the expires_at column already referenced by GenerateJWT and the role-expiry cleaner",
			UpSQL:       userRolesExpiresAtUp,
			DownSQL:     userRolesExpiresAtDown,
		},
		{
			Version:     31,
			Name:        "oauth_refresh_tokens_session_id",
			Description: "Adds the session_id column oauth_refresh_tokens has been silently failing INSERTs on since session-bound rotation landed; fixes the refresh-token grant",
			UpSQL:       oauthRefreshSessionIDUp,
			DownSQL:     oauthRefreshSessionIDDown,
		},
		{
			Version:     32,
			Name:        "privacy_tables",
			Description: "Brings privacy/GDPR tables (user_consents, data_subject_requests, privacy_retention_policies, privacy_assessments) under the migration runner — previously only created by deployments/docker/init-db.sql, so Helm/Terraform installs were missing them",
			UpSQL:       privacyTablesUp,
			DownSQL:     privacyTablesDown,
		},
		{
			Version:     33,
			Name:        "qr_login_sessions",
			Description: "Adds the qr_login_sessions table that internal/identity/passwordless.go has been INSERTing into since the QR-login feature shipped, but which no migration ever created — /oauth/qr-login/create was 500ing for every install on the first INSERT. Surfaced by the PR #126 integration tests.",
			UpSQL:       qrLoginSessionsUp,
			DownSQL:     qrLoginSessionsDown,
		},
		{
			Version:     34,
			Name:        "org_id_columns",
			Description: "Adds NULL-able org_id UUID columns + idx_<table>_org_id indexes to ~55 tables the v2.0 multi-tenancy design says must be org-scoped but that migration v025 didn't reach. Idempotent (IF NOT EXISTS). No backfill, no NOT NULL, no FK — those land in v035 and v036. Tables that are genuinely install-wide (organizations, permissions, system_settings, ip_threat_list, posture_check_types, policy_sync_state) are deliberately not scoped.",
			UpSQL:       orgIDColumnsUp,
			DownSQL:     orgIDColumnsDown,
		},
		{
			Version:     35,
			Name:        "org_id_backfill",
			Description: "Backfills the default organization UUID (00000000-0000-0000-0000-000000000010, created by v025) into every NULL org_id row across the ~55 tables v34 scoped. Idempotent (WHERE org_id IS NULL guards each UPDATE). Defensive INSERT at the top ensures the default org row exists even on installs that somehow skipped v25. No schema change, no constraint change, no behavioral change. Sets up v036 to add NOT NULL + FK.",
			UpSQL:       orgIDBackfillUp,
			DownSQL:     orgIDBackfillDown,
		},
		{
			Version:     36,
			Name:        "org_id_constraints",
			Description: "Final v1.6.0 foundation migration. For each of the 68 scoped tables: SET DEFAULT to default org UUID (preserves v1.6.0 ship gate — INSERTs that omit org_id silently land in default org), SET NOT NULL (schema correctness; v35 backfilled every row so this never rewrites data), ADD FK to organizations(id) ON DELETE RESTRICT (referential integrity), CREATE permissive RLS policy (placeholder — v1.8.0 ALTER POLICY tightens to a real org_id filter and ALTER TABLE ENABLE ROW LEVEL SECURITY activates enforcement). RLS itself is NOT enabled here; v1.8.0 owns activation.",
			UpSQL:       orgIDConstraintsUp,
			DownSQL:     orgIDConstraintsDown,
		},
		{
			Version:     37,
			Name:        "rls_activate",
			Description: "v1.8.0 RLS belt. Rewrites the 68 dormant pol_<t>_org_scope policies from USING(true) to a real tenant predicate — app.bypass_rls='on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid (fail-closed when the GUC is unset) — then ENABLE + FORCE ROW LEVEL SECURITY per table (FORCE because the app connects as the table owner). The per-request GUC is set at pool checkout from orgctx (internal/common/database); background/cross-org jobs opt into app.bypass_rls via orgctx.WithBypassRLS. Down reverts to USING(true) + RLS off.",
			UpSQL:       rlsActivateUp,
			DownSQL:     rlsActivateDown,
		},
		{
			Version:     38,
			Name:        "tenant_tables",
			Description: "Create tenant_branding, tenant_domains and tenant_settings in the versioned migration set. These back the multi-tenant login (per-org branding read by the public branding endpoint + OAuth login page) and domain-based tenant resolution. They previously lived only in deployments/docker/init-db.sql (docker-compose only), so managed-RDS/Helm deploys never had them. DDL is idempotent (IF NOT EXISTS) — a no-op on init-db.sql-bootstrapped clusters. Not placed under the RLS belt: both are read before any org context exists.",
			UpSQL:       tenantTablesUp,
			DownSQL:     tenantTablesDown,
		},
		{
			Version:     39,
			Name:        "device_trust_risk_tables",
			Description: "Create device_trust_requests, device_trust_settings, trusted_browsers and risk_policies in the versioned migration set. Their internal/identity handlers returned 500 on managed-RDS/Helm/migrate deploys because the tables existed only in deployments/docker/init-db.sql (same gap class as v38's tenant_* tables). DDL is idempotent. A wider init-db.sql↔migrations gap (~70 more tables) is tracked as separate follow-up.",
			UpSQL:       deviceTrustRiskUp,
			DownSQL:     deviceTrustRiskDown,
		},
		{
			Version:     40,
			Name:        "access_schema_reconcile",
			Description: "Fix the access-service App Publish feature on managed-RDS/Helm/migrate deploys: create published_apps, discovered_paths, service_features (init-db.sql-only tables, so /api/v1/access/apps 500'd) and add the ~12 proxy_routes columns the access code SELECTs (idp_id, route_type, remote_host/port, posture/risk/guacamole/browzer, …) that the migrations had drifted behind init-db.sql (so /api/v1/access/routes 500'd with 'column idp_id does not exist'). Idempotent.",
			UpSQL:       accessSchemaUp,
			DownSQL:     accessSchemaDown,
		},
		{
			Version:     41,
			Name:        "published_apps_public_host",
			Description: "Adds public_host + landing_path to published_apps for the one-click 'open internal app' publish flow (POST /api/v1/access/apps/:id/publish-app): public_host records the external host assigned to an app (UI display + idempotent re-publish); landing_path is where the launcher tile points for apps whose UI is not at the site root (default '/'). Idempotent (ADD COLUMN IF NOT EXISTS).",
			UpSQL:       oneClickAppsUp,
			DownSQL:     oneClickAppsDown,
		},
		{
			Version:     42,
			Name:        "reconcile_table_gap",
			Description: "Create init-db.sql-only / loose-SQL tables missing on managed-RDS/Helm/migrate installs (same class as v38–v40): abac_policies, certification_campaigns, ai_agents (init-db.sql), saml_sessions (010_add_saml_idp_tables.sql), remote_support_sessions (202605150004_remote_support.up.sql) — fixes 500s on the ABAC Policies / AI Agents / Certification Campaigns / Remote Support pages and the saml_sessions session-worker errors. Also adds certification_campaigns started_at/completed_at/total_items that the run code writes but no source created. Idempotent. (agents, recommendations, notification_digest_settings have no schema anywhere — genuinely unimplemented, tracked separately.)",
			UpSQL:       tableGapV42Up,
			DownSQL:     tableGapV42Down,
		},
		{
			Version:     43,
			Name:        "reconcile_agent_recommendation_digest_tables",
			Description: "Create the Agent Fleet / AI Recommendations / Notification Digest tables missing on managed-RDS/Helm/migrate installs (same init-db↔migrations gap as v38–v42): enrolled_agents (+ agent_posture_results, agent_enrollment_tokens) from the loose 2025*_enrolled_agents files; ai_recommendations + recommendation_history and the ai_agents children ai_agent_credentials/permissions/activity (v42 created ai_agents but not its children) from init-db.sql; notification_digests from init-db.sql. Fixes 500s on the Agent Fleet, AI Recommendations and Notification Center digest pages. Idempotent; verbatim DDL; not org-scoped (matches source + handlers).",
			UpSQL:       agentRecoDigestUp,
			DownSQL:     agentRecoDigestDown,
		},
		{
			Version:     44,
			Name:        "reconcile_kiosk_policy_tables",
			Description: "Final init-db↔migrations reconcile pass (after v38–v43): create kiosk_policies + kiosk_policy_assignments (loose file 202605150003) — fixes 500 on GET /api/v1/access/kiosk/policies — and policy_recommendations + compliance_gaps (loose file 017_add_genai_and_advanced_auth_tables) for the AI policy-suggestion / compliance-gap endpoints. Idempotent; verbatim DDL; not org-scoped (matches source + handlers).",
			UpSQL:       kioskPolicyV44Up,
			DownSQL:     kioskPolicyV44Down,
		},
		{
			Version:     45,
			Name:        "ziti_browzer_config",
			Description: "Create ziti_browzer_config (init-db.sql-only) so BrowZer bootstrap can persist its external-JWT-signer / auth-policy / dial-policy IDs + OIDC settings and GET /ziti/browzer/status reports configured state. Same init-db↔migrations gap as v42–v44. Idempotent.",
			UpSQL:       zitiBrowzerConfigUp,
			DownSQL:     zitiBrowzerConfigDown,
		},
		{
			Version:     46,
			Name:        "ziti_identities_group_attrs_synced_at",
			Description: "Add ziti_identities.group_attrs_synced_at (init-db.sql-only column) so the Ziti user-sync INSERT/resync works on migrated installs; its absence blocked BrowZer identity provisioning (externalId + auth-policy wiring). Same init-db↔migrations gap as v42–v45. Idempotent.",
			UpSQL:       zitiIdentitiesGroupSyncUp,
			DownSQL:     zitiIdentitiesGroupSyncDown,
		},
		{
			Version:     47,
			Name:        "proxy_routes_hosting_mode",
			Description: "Add proxy_routes.hosting_mode (identity|direct) for the Ziti reconciler; backfill browzer_enabled routes to 'direct', else 'identity'. Idempotent.",
			UpSQL:       hostingModeUp,
			DownSQL:     hostingModeDown,
		},
		{
			Version:     48,
			Name:        "proxy_routes_landing_path",
			Description: "Add proxy_routes.landing_path (default '/') — where a route's bare host should land; the BrowZer router emits a 302 to it when not '/'. Idempotent.",
			UpSQL:       landingPathUp,
			DownSQL:     landingPathDown,
		},
		{
			Version:     49,
			Name:        "applications_referential_integrity",
			Description: "Add applications.route_id (→proxy_routes) and applications.oauth_client_id (→oauth_clients), both ON DELETE CASCADE; backfill from the client_id string conventions so tiles/apps can't orphan. Idempotent, non-destructive.",
			UpSQL:       appReferentialIntegrityUp,
			DownSQL:     appReferentialIntegrityDown,
		},
		{
			Version:     50,
			Name:        "device_posture_results_upsert_key",
			Description: "Add UNIQUE INDEX device_posture_results(identity_id, check_id) so the agent→device posture bridge upserts one latest row per check. Idempotent.",
			UpSQL:       devicePostureUpsertKeyUp,
			DownSQL:     devicePostureUpsertKeyDown,
		},
		{
			Version:     51,
			Name:        "drop_zt_policies",
			Description: "Drop the dead ZTPolicy tables (zt_policies, zt_policy_versions). Never wired into any service; absent on real installs. Belt cleanup, idempotent (DROP ... IF EXISTS).",
			UpSQL:       ztPolicyDropUp,
			DownSQL:     ztPolicyDropDown,
		},
		{
			Version:     52,
			Name:        "reconcile_continuous_verify_columns",
			Description: "Add the init-db-only continuous-verify columns (proxy_sessions.last_verified_at/verification_failures/geo_country/geo_city/idp_id/device_trusted; user_sessions.device_trusted + index) so the continuous session verifier's query works on migrate-based installs. Idempotent; Down is a no-op.",
			UpSQL:       continuousVerifyColumnsUp,
			DownSQL:     continuousVerifyColumnsDown,
		},
		{
			Version:     53,
			Name:        "provision_openidx_app_role",
			Description: "Provision the openidx_app NOSUPERUSER NOBYPASSRLS runtime role with blanket DML grants + default privileges, so the v37 FORCE'd RLS policies enforce once the app cuts its DATABASE_URL over to it. Passwordless (set at deploy). Migrations/DDL stay on the owner. Idempotent.",
			UpSQL:       rlsAppRoleUp,
			DownSQL:     rlsAppRoleDown,
		},
		{
			Version:     54,
			Name:        "reconcile_initdb_table_gap",
			Description: "Create the 58 tables that existed only in deployments/docker/init-db.sql so managed-Postgres/RDS/Helm/migrate installs stop 500ing across MFA variants, SAML/social/federation, lifecycle, ISPM, audit archival, bulk-ops, biometric, passwordless, guacamole and ziti-fabric features (the broad init-db<->migrations reconcile after v38-v45's ~15). Verbatim DDL, idempotent (IF NOT EXISTS) so it is a no-op on docker-compose installs. Not under the v37 RLS belt (non-FORCE tables; openidx_app unaffected). TestInitDBParity now keeps this gap from recurring.",
			UpSQL:       reconcileTableGapUp,
			DownSQL:     reconcileTableGapDown,
		},
		{
			Version:     55,
			Name:        "lifecycle_policy_executions",
			Description: "Split the deprovisioning policy-run execution log out of the workflow lifecycle_executions table (a name collision: the workflow schema won, so deprovisioning's policy_id queries failed on every install). Creates lifecycle_policy_executions; init-db.sql's dead second block is renamed in lockstep and internal/admin/deprovisioning.go repointed. Idempotent; not under the v37 RLS belt.",
			UpSQL:       lifecyclePolicyExecUp,
			DownSQL:     lifecyclePolicyExecDown,
		},
		{
			Version:     56,
			Name:        "vault_store",
			Description: "PAM credential vault store (M1): vault_secrets, vault_secret_versions, vault_access_grants, vault_checkouts — org-scoped under the v37 FORCE-RLS belt. Envelope ciphertext lives only in vault_secret_versions. Rotation (credential_rotation_policies) is deferred to M1b. Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       vaultStoreUp,
			DownSQL:     vaultStoreDown,
		},
		{
			Version:     57,
			Name:        "credential_rotation",
			Description: "PAM rotation engine (M1b): adds credential_rotation_policies (one-per-secret connector + schedule) and reconciles the dead credential_rotations table into a run ledger (org_id, policy_id, secret_id, version_from/to, connector_type, trigger, error_message, started_at, completed_at; service_account_id NOT NULL dropped). Both tables placed under the v37 FORCE-RLS belt. Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       credentialRotationUp,
			DownSQL:     credentialRotationDown,
		},
		{
			Version:     58,
			Name:        "jit_approval_drift_fix",
			Description: "Create jit_grants and request_approval_chains — referenced by internal/governance (jit.go, jit_expiry.go, request.go) but never created by any migration or init-db.sql, so POST /api/v1/governance/requests and the JIT/escalation background workers 500 today. Columns match the code's exact SQL usage. Not under the v37 RLS belt (jit_grants isn't org-scoped in code; request_approval_chains is a child of access_requests reached via the RLS-scoped parent) — matches the v42-v55 reconcile precedent. Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       jitDriftFixUp,
			DownSQL:     jitDriftFixDown,
		},
		{
			Version:     59,
			Name:        "guacamole_session_injection",
			Description: "PAM M3 session injection: adds vault_secret_id, inject_username, require_approval, record_session columns to guacamole_connections; creates guacamole_session_requests (pre-session approval lifecycle) and guacamole_sessions (active/ended session tracking + recording ledger), both under the v37 FORCE-RLS belt. guacamole_connections is not belted (only ALTERed). Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       guacSessionsUp,
			DownSQL:     guacSessionsDown,
		},
		{
			Version:     60,
			Name:        "guacamole_transcripts",
			Description: "PAM M4 session assurance: adds transcript_path (TEXT) and transcript_generated_at (TIMESTAMPTZ) to guacamole_sessions so the session-assurance sweeper can track guacd-native transcript files independently of the recording blob. Idempotent (ADD COLUMN IF NOT EXISTS); mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       guacTranscriptUp,
			DownSQL:     guacTranscriptDown,
		},
		{
			Version:     61,
			Name:        "attestation_org_isolation",
			Description: "Attestation tenant isolation: adds org_id (backfilled, NOT NULL, FK) to attestation_campaigns and attestation_items — created by v54 without org_id and queried without an org filter, a cross-org read/write exposure — and places both under the v37 FORCE-RLS belt (USING + WITH CHECK). Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       attestationOrgIsolationUp,
			DownSQL:     attestationOrgIsolationDown,
		},
		{
			Version:     62,
			Name:        "reconcile_missing_tables",
			Description: "Reconcile referenced-but-uncreated tables (drift class of v58): creates admin_console_settings, auth_contexts, breach_incidents, breach_alerts — referenced by internal/admin (settings.go, continuous_auth.go, ibdr.go) but created by neither a migration nor init-db.sql, so their endpoints 500. Columns match the code's exact SQL usage. Not RLS-belted (code doesn't org-scope them; org_id/RLS is a separate follow-up). Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       reconcileMissingTablesUp,
			DownSQL:     reconcileMissingTablesDown,
		},
		{
			Version:     63,
			Name:        "column_drift_reconcile",
			Description: "Reconcile init-db<->migrations COLUMN drift (paired with the new column-aware TestInitDBColumnParity). Fixes ziti_certificates (swaps the stale migration schema {cert_data NOT NULL, private_key_encrypted, ca_chain, expires_at, identity_id} for the code/init-db schema {cert_type, subject, issuer, serial_number, fingerprint, not_before, not_after, auto_renew, renewal_threshold_days, pem_data, status, associated_identity_id} + indexes) and adds columns init-db.sql adds via ALTER but no migration did, across application_sso_settings, directory_sync_state, ip_threat_list, oauth_clients, user_roles, user_sessions, users, ziti_service_policies. All idempotent; init-db.sql already defines these so it is unchanged.",
			UpSQL:       columnDriftReconcileUp,
			DownSQL:     columnDriftReconcileDown,
		},
		{
			Version:     64,
			Name:        "jit_approval_org_rls",
			Description: "Defense-in-depth: adds org_id (backfilled from the user/parent-request, NOT NULL, FK) to jit_grants and request_approval_chains and places both under the v37 FORCE-RLS belt (USING + WITH CHECK). v58 created them belt-less (org-scoped only via FKs/parent); the cross-org background sweeps already run under WithBypassRLS so the belt doesn't break them. Idempotent; mirrored into init-db.sql so TestInitDBParity stays green.",
			UpSQL:       jitApprovalOrgRLSUp,
			DownSQL:     jitApprovalOrgRLSDown,
		},
		{
			Version:     65,
			Name:        "webhook_secret_widen",
			Description: "Widen webhook_subscriptions.secret to TEXT so the HMAC signing secret can be stored AES-256-GCM-encrypted at rest (secretcrypt, tag encv1:) instead of plaintext — base64 ciphertext exceeds VARCHAR(255). Encryption is applied by the webhooks service (encrypt-on-write, prefix-aware decrypt-on-read); legacy plaintext rows read through unchanged and sign correctly, and are migrated by a one-off backfill tool (UpdateSubscription doesn't rewrite the secret). Idempotent; init-db.sql defines the column as TEXT directly.",
			UpSQL:       webhookSecretWidenUp,
			DownSQL:     webhookSecretWidenDown,
		},
		{
			Version:     66,
			Name:        "idp_client_secret_widen",
			Description: "Widen identity_providers.client_secret to TEXT so the external-IdP OIDC client secret can be stored AES-256-GCM-encrypted at rest (secretcrypt, tag encv1:) instead of plaintext — base64 ciphertext exceeds VARCHAR(255). identity encrypts on create/update + decrypts on read; access (multi_idp) decrypts its direct reads; oauth reads via identity.GetIdentityProvider. Prefix-aware reads keep legacy plaintext rows working and re-encrypt on Update; any never-updated rows migrate by re-saving the IdP at deploy. Idempotent; init-db.sql defines the column as TEXT.",
			UpSQL:       idpClientSecretWidenUp,
			DownSQL:     idpClientSecretWidenDown,
		},
		{
			Version:     67,
			Name:        "guac_token_widen",
			Description: "Widen guacamole_connection_pool.token to TEXT so the pooled Guacamole session token can be stored AES-256-GCM-encrypted at rest (secretcrypt, tag encv1:) instead of plaintext — base64 ciphertext exceeds VARCHAR(500). The column is write-only (in-memory pool serves reads), so the access service only encrypts on write; a DB dump yields no usable tokens. Idempotent; init-db.sql defines the column as TEXT.",
			UpSQL:       guacTokenWidenUp,
			DownSQL:     guacTokenWidenDown,
		},
		{
			Version:     68,
			Name:        "guacamole_recording_legal_hold",
			Description: "Guacamole recording legal-hold: guacamole_recording_legal_holds (FK -> guacamole_sessions ON DELETE CASCADE, UNIQUE active-hold partial index) so sweepExpiredGuacRecordings never purges a held recording. Parallels recording_legal_holds (v42, remote_support). Not RLS-belted; plain GRANT to openidx_app (exists by v53). Idempotent.",
			UpSQL:       guacRecordingLegalHoldsUp,
			DownSQL:     guacRecordingLegalHoldsDown,
		},
		{
			Version:     69,
			Name:        "governance_org_isolation",
			Description: "Add org_id + FORCE RLS to certification_campaigns, campaign_runs, abac_policies",
			UpSQL:       governanceOrgIsolationUp,
			DownSQL:     governanceOrgIsolationDown,
		},
		{
			Version:     70,
			Name:        "users_manager_id",
			Description: "Add the self-referential users.manager_id (nullable, ON DELETE SET NULL) + index that certification resolveReviewer's manager strategy already queries but no migration created — its absence made every 'manager' campaign silently fall back to the system admin. Populated from the SCIM enterprise-extension manager.value. No backfill; users is already under the v37 RLS belt (RI checks bypass RLS, so the self-FK resolves cross-GUC). Idempotent.",
			UpSQL:       usersManagerIDUp,
			DownSQL:     usersManagerIDDown,
		},
		{
			Version:     71,
			Name:        "temp_access_links_org_isolation",
			Description: "Add org_id (backfilled from the creating user, NOT NULL, FK) + index to temp_access_links (PAM vendor SSH/RDP/VNC access, created by v54 with no org_id). Its list/get/revoke handlers filtered by id only — a cross-tenant IDOR letting any authenticated user enumerate/read/revoke every org's access links. Handlers now add an org predicate + admin gate. Deliberately NOT RLS-belted: the public token-redemption path has no org context and the token is a unique secret. Idempotent.",
			UpSQL:       tempAccessOrgIsolationUp,
			DownSQL:     tempAccessOrgIsolationDown,
		},
		{
			Version:     72,
			Name:        "device_trust_requests_org_isolation",
			Description: "Add org_id (backfilled from the requesting user, NOT NULL, FK) + index to device_trust_requests (admin device-trust approval workflow, created by v39 with no org_id). Its approve/reject acted by bare id and its COUNT queries had no org filter — a cross-tenant IDOR letting an admin approve/reject another org's requests and read global pending counts. Service methods now carry an org predicate. Not RLS-belted (ExpireOldRequests sweeps across orgs). Idempotent.",
			UpSQL:       deviceTrustReqOrgIsolationUp,
			DownSQL:     deviceTrustReqOrgIsolationDown,
		},
		{
			Version:     73,
			Name:        "published_apps_org_isolation",
			Description: "Add org_id (published_apps backfilled from created_by's org, discovered_paths from its parent app; orphans -> oldest org; NOT NULL, FK ON DELETE CASCADE) + indexes to published_apps and discovered_paths (access App-Publish tables, created by v40 with no org_id). The app-publish handlers acted on rows by bare id with no org filter — a cross-tenant IDOR letting any caller list/read/delete another org's apps and paths. Handlers now carry an org predicate. Not RLS-belted (runAppDiscovery runs in a background goroutine with no org ctx; the integrity doctor sweeps all orgs under bypass-RLS). Idempotent.",
			UpSQL:       publishedAppsOrgIsolationUp,
			DownSQL:     publishedAppsOrgIsolationDown,
		},
		{
			Version:     74,
			Name:        "detailed_compliance_reports",
			Description: "Create the detailed_compliance_reports table (org-scoped: org_id NOT NULL, FK ON DELETE CASCADE, indexes). internal/audit's storeDetailedReport persisted every generated SOC 2 / ISO 27001 detailed report into this table, but no migration created it — every INSERT silently failed and GET /reports/:id/evidence always degraded to the basic compliance_reports fallback, so control-level evidence was never downloadable. The audit queries now carry an explicit org predicate (read is scoped by id AND org_id, closing the would-be cross-tenant evidence fetch). Not RLS-belted, matching v72/v73 precedent. Idempotent.",
			UpSQL:       detailedComplianceReportsUp,
			DownSQL:     detailedComplianceReportsDown,
		},
		{
			Version:     75,
			Name:        "known_devices_device_type",
			Description: "Add device_type VARCHAR(50) to known_devices. isCorporateDevice (device-trust auto-approval) filtered on this column, which v19 never created: the query errored on every call, the error was swallowed, and the check always returned false — the auto_approve_corporate_devices org setting (v39) was silently inert. With the column present the name-based corporate match works with existing rows and device_type='corporate' can be set by MDM/admin tooling. Idempotent.",
			UpSQL:       knownDevicesDeviceTypeUp,
			DownSQL:     knownDevicesDeviceTypeDown,
		},
		{
			Version:     76,
			Name:        "known_devices_seen_count",
			Description: "Add seen_count INTEGER NOT NULL DEFAULT 1 to known_devices and retenant portal-registered rows that fell into the primary org by column DEFAULT while their owner belongs to another org. The risk engine's device fingerprinting read/wrote seen_count plus first_seen/last_seen columns v19 never created — the new-device INSERT failed on every call, so risk device tracking never recorded a device and trust levels never progressed. Code now uses created_at/last_seen_at for the timestamps; seen_count is the one column with no existing equivalent. The retenant UPDATE corrects data mis-tenanted by the pre-fix portal RegisterDevice (fix shipped separately) and is not reversed on down. Idempotent.",
			UpSQL:       knownDevicesSeenCountUp,
			DownSQL:     knownDevicesSeenCountDown,
		},
		{
			Version:     77,
			Name:        "session_risk_history",
			Description: "Create session_risks and risk_factors for the routed continuous-auth endpoints (internal/admin/continuous_auth.go). Both tables were read and written on every risk calculation but existed in no runner migration: the previous-risk lookup and history INSERT silently failed (errors discarded), so risk deltas were always computed against 0, no history was stored, and GetRiskFactors errored outright. Org-belted (org_id NOT NULL FK) like stepup_challenges. Idempotent.",
			UpSQL:       sessionRiskHistoryUp,
			DownSQL:     sessionRiskHistoryDown,
		},
		{
			Version:     78,
			Name:        "recording_retention_policies",
			Description: "Create recording_retention_policies for the live per-org remote-support recording retention surface (internal/access/remote_support_retention.go). The GET/PUT /recording-retention-policy routes are mounted by RegisterRetentionAdminRoutes and the background retention enforcer consults the table on every sweep, but no runner migration created it: both routes 500'd and resolveEffectiveRetention silently fell through to the global default, so per-org retention was configurable in name only. org_id PRIMARY KEY (handlers upsert ON CONFLICT (org_id)); retention_days 0 = infinite per the handler contract, CHECK >= 0. Idempotent.",
			UpSQL:       recordingRetentionPoliciesUp,
			DownSQL:     recordingRetentionPoliciesDown,
		},
		{
			Version:     79,
			Name:        "oauth_signing_keys",
			Description: "Create oauth_signing_keys for DB-backed signing key rotation (internal/signingkeys). The OAuth service previously held a single RSA key in system_settings hardcoded to kid openidx-key-1, so rotation was impossible without invalidating every outstanding token. One active key (enforced by a partial unique index, which also gives EnsureActive a race-safe ON CONFLICT target) plus retired keys servable from JWKS until not_after. The legacy system_settings key is imported under its original kid on first boot so pre-upgrade tokens keep verifying. Install-wide (no org_id) like system_settings; private_key_pem encrypted at rest via ENCRYPTION_KEY. Idempotent.",
			UpSQL:       oauthSigningKeysUp,
			DownSQL:     oauthSigningKeysDown,
		},
		{
			Version:     80,
			Name:        "enrolled_agent_device_link",
			Description: "Add enrolled_agents.known_device_id FK to converge the two per-user device registries. known_devices (IAM device-trust: fingerprints + trusted flag) and enrolled_agents (Ziti endpoint agents with posture/compliance) were disjoint, so device trust and device compliance could never be reconciled for one physical device. The user-bound (OAuth) agent-enrollment path now upserts+links a known_devices row; token-enrolled and legacy agents keep known_device_id NULL. ON DELETE SET NULL. Idempotent.",
			UpSQL:       enrolledAgentDeviceLinkUp,
			DownSQL:     enrolledAgentDeviceLinkDown,
		},
		{
			Version:     81,
			Name:        "pam_connection_manager",
			Description: "PAM connection manager (Devolutions RDM parity): pam_folders (hierarchical tree), pam_entries (typed entries — rdp/ssh/vnc/telnet/website sessions, credentials, ssh keys, api keys, secure information records — with secret payloads envelope-encrypted in vault_secrets and an optional linked credential entry), pam_entry_grants (view/connect/edit/reveal ACL), pam_entry_favorites, pam_entry_access_requests (pre-connect approval), pam_entry_sessions (launch ledger). Sessions launch through the Guacamole broker with the credential injected server-side so users connect without ever seeing the password. All six tables org-scoped under the v37 FORCE-RLS belt. Idempotent.",
			UpSQL:       pamEntriesUp,
			DownSQL:     pamEntriesDown,
		},
		{
			Version:     82,
			Name:        "pam_entry_reach_mode",
			Description: "Add pam_entries.reach_mode (direct|ziti), ziti_service_name, ziti_intercept_port so a brokered PAM session can reach its target over the OpenZiti overlay (guacd → loopback → ziti-tunnel → edge-router-hosted host.v1 → target) instead of guacd dialing the target directly — removing inbound target exposure. Additive/idempotent; existing entries default to 'direct'. Partial unique index on (org_id, ziti_intercept_port) prevents broker loopback-port collisions.",
			UpSQL:       pamReachModeUp,
			DownSQL:     pamReachModeDown,
		},
		{
			Version:     83,
			Name:        "saml_sp_schema_reconcile",
			Description: "Reconcile saml_service_providers to the columns internal/oauth/saml_sp.go reads/writes (description, metadata_url, want_assertions_signed, encryption_enabled, last_used_at) — the SP list/create/update paths were erroring with 42703 (column does not exist). Additive/idempotent; TEXT cols NOT NULL DEFAULT '', booleans default false, last_used_at nullable.",
			UpSQL:       samlSPReconcileUp,
			DownSQL:     samlSPReconcileDown,
		},
		{
			Version:     84,
			Name:        "seed_mobile_oauth_client",
			Description: "Seed the openidx-mobile public (PKCE) OAuth client with the native redirect openidx://oauth-callback and refresh tokens, so the companion mobile app's login works on every install. Idempotent (ON CONFLICT DO NOTHING).",
			UpSQL:       mobileClientUp,
			DownSQL:     mobileClientDown,
		},
		{
			Version:     85,
			Name:        "seed_desktop_oauth_client",
			Description: "Seed the openidx-desktop public (PKCE) OAuth client with a fixed loopback redirect (http://127.0.0.1:47600/callback) so the Windows client's SSO works on every install. Idempotent (ON CONFLICT DO NOTHING).",
			UpSQL:       desktopClientUp,
			DownSQL:     desktopClientDown,
		},
		{
			Version:     86,
			Name:        "reusable_enrollment_tokens",
			Description: "Add agent_enrollment_tokens.reusable so a single bootstrap token can enroll a whole fleet (MDM/GPO/Intune) without being consumed. Enrollment validation skips the single-use check for reusable tokens. Additive/idempotent.",
			UpSQL:       reusableTokensUp,
			DownSQL:     reusableTokensDown,
		},
		{
			Version:     87,
			Name:        "guacamole_per_user_identities",
			Description: "Per-user non-admin Guacamole accounts (guacamole_users) + pam_entry_sessions.guac_username so PAM sessions broker under a per-user identity scoped to a single connection instead of the shared admin token. Additive/idempotent.",
			UpSQL:       guacPerUserUp,
			DownSQL:     guacPerUserDown,
		},
		{
			Version:     88,
			Name:        "audit_es_reconcile_watermark",
			Description: "Add audit_events.indexed_at (+ partial index) so a background reconciler can backfill any audit event the fire-and-forget Elasticsearch write missed, guaranteeing ES search completeness. Additive/idempotent.",
			UpSQL:       auditIndexedAtUp,
			DownSQL:     auditIndexedAtDown,
		},
		{
			Version:     89,
			Name:        "oauth_user_consents",
			Description: "Add oauth_user_consents so application_sso_settings.require_consent is enforceable: the authorize flow records a user's scope grant per client and re-prompts only when requested scopes exceed the stored grant. Org-scoped under FORCE RLS. Additive/idempotent.",
			UpSQL:       oauthUserConsentsUp,
			DownSQL:     oauthUserConsentsDown,
		},
		{
			Version:     90,
			Name:        "pam_entries_renderer",
			Description: "Add pam_entries.renderer (guacamole|wasm-ssh|novnc|support) so a PAM entry can declare which clientless in-browser renderer opens it; backfill existing rows to 'guacamole' (no behavior change). The permission/approval gate is unchanged and applies to every renderer. Additive/idempotent.",
			UpSQL:       pamEntryRendererUp,
			DownSQL:     pamEntryRendererDown,
		},
		{
			Version:     91,
			Name:        "quick_links",
			Description: "Add quick_links: an admin-curated, user-searchable launcher for support/collaboration systems. type='external' opens a URL; type='pam' references a pam_entries row and launches it clientlessly via the entry's renderer (guacamole/wasm-ssh) under the existing PAM permission gate. Org-scoped + forced RLS; role-gated by min_role. Additive/idempotent.",
			UpSQL:       quickLinksUp,
			DownSQL:     quickLinksDown,
		},
		{
			Version:     92,
			Name:        "remote_support_consent",
			Description: "Add remote_support_sessions.consent_required/consent_status/consent_decided_at so an attended support session can require the person at the device to click Allow before the admin can view/control. Existing sessions default consent_required=false (no behavior change for unattended/server support). Additive/idempotent.",
			UpSQL:       remoteSupportConsentUp,
			DownSQL:     remoteSupportConsentDown,
		},
		{
			Version:     93,
			Name:        "device_fingerprint",
			Description: "Add enrolled_agents.device_fingerprint + a partial unique index so re-enrollment of the same physical device reuses one agent_id/auth_token instead of minting a new row every install. Existing rows keep fingerprint NULL and are unaffected. Additive/idempotent.",
			UpSQL:       deviceFingerprintUp,
			DownSQL:     deviceFingerprintDown,
		},
		{
			Version:     94,
			Name:        "remote_support_transport",
			Description: "Add remote_support_sessions.transport (webrtc|relay) so a session can use a fully server-relayed VP8-over-WebSocket media path instead of peer-to-peer WebRTC. Defaults to 'webrtc' (no behavior change). Enables full-Ziti, no-STUN remote support.",
			UpSQL:       remoteSupportTransportUp,
			DownSQL:     remoteSupportTransportDown,
		},
		{
			Version:     95,
			Name:        "outbound_scim",
			Description: "Add scim_target_apps + scim_provisioning_records + scim_provisioning_queue so OpenIDX can act as a SCIM 2.0 client and provision users/groups OUT to downstream SaaS (Okta/Entra/Slack/...). Outbox-based at-least-once delivery with retry/backoff. Org-scoped for RLS. Additive/idempotent; no behavior change until a target app is configured.",
			UpSQL:       outboundScimUp,
			DownSQL:     outboundScimDown,
		},
		{
			Version:     96,
			Name:        "hr_jml",
			Description: "Add HR/JML user attributes (employee_number, job_title, department, hire_date, termination_date, employment_status, external_hr_id) + supporting indexes so an HRIS source (BambooHR/Workday/SuccessFactors, modeled as a directory-connector type) can drive joiner/mover/leaver. Additive/idempotent; NULL for existing users.",
			UpSQL:       hrJmlUp,
			DownSQL:     hrJmlDown,
		},
		{
			Version:     97,
			Name:        "dcr_registration_tokens",
			Description: "Add oauth_registration_tokens (hashed RFC 7592 registration access token per dynamically-registered client) so an RFC 7591-registered client can manage its own credential lifecycle. Token Exchange (RFC 8693) needs no schema. Additive/idempotent.",
			UpSQL:       dcrTokenExchangeUp,
			DownSQL:     dcrTokenExchangeDown,
		},
		{
			Version:     98,
			Name:        "edr_posture_ingestion",
			Description: "Add edr_posture_sources + edr_device_mappings so an external EDR/MDM (CrowdStrike/Intune/Jamf) can feed the existing Ziti-bound posture pipeline: a non-compliant device signal writes a failing device_posture_results row, so the proxy/continuous-verify enforcement revokes the session and severs the overlay circuit automatically. Org-scoped, encrypted creds. Additive/idempotent.",
			UpSQL:       edrPostureUp,
			DownSQL:     edrPostureDown,
		},
		{
			Version:     99,
			Name:        "ssf_caep",
			Description: "Add ssf_streams + ssf_stream_delivery (outbox) + ssf_received_events so OpenIDX is both an SSF/CAEP transmitter (push signed SETs on session-revoked etc.) and receiver (apply inbound SETs, with Ziti session termination as the actuator). Org-scoped, encrypted delivery auth. Additive/idempotent.",
			UpSQL:       ssfCaepUp,
			DownSQL:     ssfCaepDown,
		},
		{
			Version:     100,
			Name:        "network_revocation_queue",
			Description: "Add network_revocation_queue so the governance service can hand a circuit-severance intent to the access-service (which owns the ZitiManager) on an access-review/certification revoke or JIT expiry. A worker terminates the subject's live overlay circuits, completing decision-to-packet. Additive/idempotent.",
			UpSQL:       networkRevocationQueueUp,
			DownSQL:     networkRevocationQueueDown,
		},
		{
			Version:     101,
			Name:        "network_grant_queue",
			Description: "Add network_grant_queue (+ network_revocation_queue.attribute) for JIT network grants (Wave B1): fulfilling a network_service access request adds a time-bound Ziti role attribute (jit-<request-id>) that opens the dial; expiry removes it and severs the circuit. Governance->access handoff. Additive/idempotent.",
			UpSQL:       networkGrantQueueUp,
			DownSQL:     networkGrantQueueDown,
		},
		{
			Version:     102,
			Name:        "usage_metering",
			Description: "Add usage_metering_daily + usage_metering_cursor (Wave A4): a daily rollup of Ziti fabric usage (overlay logins, service dials) from unified_audit_events, per org/service/identity. The MSP billing substrate. Additive/idempotent.",
			UpSQL:       usageMeteringUp,
			DownSQL:     usageMeteringDown,
		},
	}
}
