//go:build !embed_migrations

package migrations

// LoadMigrations loads all migrations from the embedded filesystem
func (m *Migrator) LoadMigrations() ([]*Migration, error) {
	// For embedded migrations, use predefined list
	return allMigrations(), nil
}

// allMigrations returns the complete list of migrations
// This is generated from the migrations directory
func allMigrations() []*Migration {
	return []*Migration{
		{
			Version:     1,
			Name:        "initial_schema",
			Description: "Initial database schema with core tables",
			UpSQL:       initialSchemaUp,
			DownSQL:     initialSchemaDown,
		},
		{
			Version:     2,
			Name:        "oauth_oidc",
			Description: "OAuth 2.0 / OIDC tables",
			UpSQL:       oauthOIDCUp,
			DownSQL:     oauthOIDCDown,
		},
		{
			Version:     3,
			Name:        "scim",
			Description: "SCIM 2.0 provisioning tables",
			UpSQL:       scimUp,
			DownSQL:     scimDown,
		},
		{
			Version:     4,
			Name:        "governance",
			Description: "Governance tables for access reviews and policies",
			UpSQL:       governanceUp,
			DownSQL:     governanceDown,
		},
		{
			Version:     5,
			Name:        "mfa",
			Description: "Multi-factor authentication tables (TOTP, WebAuthn, Push)",
			UpSQL:       mfaUp,
			DownSQL:     mfaDown,
		},
		{
			Version:     6,
			Name:        "sessions",
			Description: "Session management tables",
			UpSQL:       sessionsUp,
			DownSQL:     sessionsDown,
		},
		{
			Version:     7,
			Name:        "applications",
			Description: "Application management tables",
			UpSQL:       applicationsUp,
			DownSQL:     applicationsDown,
		},
		{
			Version:     8,
			Name:        "audit_compliance",
			Description: "Audit and compliance tables",
			UpSQL:       auditComplianceUp,
			DownSQL:     auditComplianceDown,
		},
		{
			Version:     9,
			Name:        "indexes",
			Description: "Performance indexes",
			UpSQL:       indexesUp,
			DownSQL:     indexesDown,
		},
		{
			Version:     10,
			Name:        "seed_data",
			Description: "Initial seed data (admin user, roles, groups)",
			UpSQL:       seedDataUp,
			DownSQL:     seedDataDown,
		},
		{
			Version:     11,
			Name:        "identity_providers",
			Description: "External identity provider integration (OIDC/SAML)",
			UpSQL:       identityProvidersUp,
			DownSQL:     identityProvidersDown,
		},
		{
			Version:     12,
			Name:        "provisioning_rules",
			Description: "Provisioning rules and password reset tokens",
			UpSQL:       provisioningRulesUp,
			DownSQL:     provisioningRulesDown,
		},
		{
			Version:     13,
			Name:        "permissions",
			Description: "Permissions and role permissions tables",
			UpSQL:       permissionsUp,
			DownSQL:     permissionsDown,
		},
		{
			Version:     14,
			Name:        "system_settings",
			Description: "System settings and configuration",
			UpSQL:       systemSettingsUp,
			DownSQL:     systemSettingsDown,
		},
		{
			Version:     15,
			Name:        "directory_integrations",
			Description: "Directory integration tables",
			UpSQL:       directoryIntegrationsUp,
			DownSQL:     directoryIntegrationsDown,
		},
		{
			Version:     16,
			Name:        "proxy_routes",
			Description: "Zero Trust Access Proxy routes and sessions",
			UpSQL:       proxyRoutesUp,
			DownSQL:     proxyRoutesDown,
		},
		{
			Version:     17,
			Name:        "openziti",
			Description: "OpenZiti integration tables",
			UpSQL:       openzitiUp,
			DownSQL:     openzitiDown,
		},
		{
			Version:     18,
			Name:        "directory_sync",
			Description: "Directory sync state and logs",
			UpSQL:       directorySyncUp,
			DownSQL:     directorySyncDown,
		},
		{
			Version:     19,
			Name:        "conditional_access",
			Description: "Conditional access and risk engine tables",
			UpSQL:       conditionalAccessUp,
			DownSQL:     conditionalAccessDown,
		},
		{
			Version:     20,
			Name:        "api_keys_webhooks",
			Description: "API keys, webhooks, email verification, invitations",
			UpSQL:       apiKeysWebhooksUp,
			DownSQL:     apiKeysWebhooksDown,
		},
		{
			Version:     21,
			Name:        "access_requests",
			Description: "Access request and approval workflow tables",
			UpSQL:       accessRequestsUp,
			DownSQL:     accessRequestsDown,
		},
		{
			Version:     22,
			Name:        "security_alerts",
			Description: "Security alerts and anomaly detection",
			UpSQL:       securityAlertsUp,
			DownSQL:     securityAlertsDown,
		},
		{
			Version:     23,
			Name:        "password_management",
			Description: "Password history and credential rotation",
			UpSQL:       passwordManagementUp,
			DownSQL:     passwordManagementDown,
		},
		{
			Version:     24,
			Name:        "session_enhancements",
			Description: "Session management enhancements",
			UpSQL:       sessionEnhancementsUp,
			DownSQL:     sessionEnhancementsDown,
		},
		{
			Version:     25,
			Name:        "multitenancy",
			Description: "Multi-tenancy support with organizations",
			UpSQL:       multitenancyUp,
			DownSQL:     multitenancyDown,
		},
		{
			Version:     26,
			Name:        "reporting",
			Description: "Advanced reporting tables",
			UpSQL:       reportingUp,
			DownSQL:     reportingDown,
		},
		{
			Version:     27,
			Name:        "self_service",
			Description: "Self-service portal tables",
			UpSQL:       selfServiceUp,
			DownSQL:     selfServiceDown,
		},
		{
			Version:     28,
			Name:        "notifications",
			Description: "Notification system tables",
			UpSQL:       notificationsUp,
			DownSQL:     notificationsDown,
		},
		{
			Version:     29,
			Name:        "ziti_enhanced",
			Description: "OpenZiti enhanced features (posture checks, policy sync)",
			UpSQL:       zitiEnhancedUp,
			DownSQL:     zitiEnhancedDown,
		},
		{
			Version:     30,
			Name:        "user_roles_expires_at",
			Description: "Time-bound role assignments: adds the expires_at column already referenced by GenerateJWT and the role-expiry cleaner",
			UpSQL:       userRolesExpiresAtUp,
			DownSQL:     userRolesExpiresAtDown,
		},
		{
			Version:     31,
			Name:        "oauth_refresh_tokens_session_id",
			Description: "Adds the session_id column oauth_refresh_tokens has been silently failing INSERTs on since session-bound rotation landed; fixes the refresh-token grant",
			UpSQL:       oauthRefreshSessionIDUp,
			DownSQL:     oauthRefreshSessionIDDown,
		},
		{
			Version:     32,
			Name:        "privacy_tables",
			Description: "Brings privacy/GDPR tables (user_consents, data_subject_requests, privacy_retention_policies, privacy_assessments) under the migration runner — previously only created by deployments/docker/init-db.sql, so Helm/Terraform installs were missing them",
			UpSQL:       privacyTablesUp,
			DownSQL:     privacyTablesDown,
		},
		{
			Version:     33,
			Name:        "qr_login_sessions",
			Description: "Adds the qr_login_sessions table that internal/identity/passwordless.go has been INSERTing into since the QR-login feature shipped, but which no migration ever created — /oauth/qr-login/create was 500ing for every install on the first INSERT. Surfaced by the PR #126 integration tests.",
			UpSQL:       qrLoginSessionsUp,
			DownSQL:     qrLoginSessionsDown,
		},
		{
			Version:     34,
			Name:        "org_id_columns",
			Description: "Adds NULL-able org_id UUID columns + idx_<table>_org_id indexes to ~55 tables the v2.0 multi-tenancy design says must be org-scoped but that migration v025 didn't reach. Idempotent (IF NOT EXISTS). No backfill, no NOT NULL, no FK — those land in v035 and v036. Tables that are genuinely install-wide (organizations, permissions, system_settings, ip_threat_list, posture_check_types, policy_sync_state) are deliberately not scoped.",
			UpSQL:       orgIDColumnsUp,
			DownSQL:     orgIDColumnsDown,
		},
		{
			Version:     35,
			Name:        "org_id_backfill",
			Description: "Backfills the default organization UUID (00000000-0000-0000-0000-000000000010, created by v025) into every NULL org_id row across the ~55 tables v34 scoped. Idempotent (WHERE org_id IS NULL guards each UPDATE). Defensive INSERT at the top ensures the default org row exists even on installs that somehow skipped v25. No schema change, no constraint change, no behavioral change. Sets up v036 to add NOT NULL + FK.",
			UpSQL:       orgIDBackfillUp,
			DownSQL:     orgIDBackfillDown,
		},
	}
}
