package migrations

// Migration v37 — v1.8.0 RLS belt activation.
//
// v36 created dormant permissive policies (pol_<t>_org_scope, USING (true)) on
// all 68 org-scoped tables but left RLS disabled. v37 rewrites each policy to a
// real tenant predicate and turns RLS on with FORCE (the app connects as the
// table owner, so FORCE is required for the policy to apply to it).
//
// Predicate: app.bypass_rls='on' (legitimate cross-org/background work, set via
// orgctx.WithBypassRLS → the pool checkout hook) OR the row's org_id equals the
// session's app.org_id GUC. When app.org_id is unset/empty the predicate is
// org_id = NULL → no rows (fail-closed).
var rlsActivateUp = `-- Migration 037: activate Row-Level Security on the 68 org-scoped tables.
ALTER POLICY pol_users_org_scope ON users USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_groups_org_scope ON groups USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE groups FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_roles_org_scope ON roles USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_applications_org_scope ON applications USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_oauth_clients_org_scope ON oauth_clients USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE oauth_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_clients FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_audit_events_org_scope ON audit_events USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_sessions_org_scope ON sessions USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_policies_org_scope ON policies USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE policies FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_access_reviews_org_scope ON access_reviews USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE access_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_reviews FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_service_accounts_org_scope ON service_accounts USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE service_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_accounts FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_webhook_subscriptions_org_scope ON webhook_subscriptions USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE webhook_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_subscriptions FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_access_requests_org_scope ON access_requests USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE access_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_requests FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_security_alerts_org_scope ON security_alerts USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE security_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_alerts FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_notifications_org_scope ON notifications USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_api_keys_org_scope ON api_keys USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_email_verification_tokens_org_scope ON email_verification_tokens USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE email_verification_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_verification_tokens FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_known_devices_org_scope ON known_devices USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE known_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE known_devices FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_login_history_org_scope ON login_history USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE login_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE login_history FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_notification_preferences_org_scope ON notification_preferences USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_password_history_org_scope ON password_history USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE password_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_history FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_password_reset_tokens_org_scope ON password_reset_tokens USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_qr_login_sessions_org_scope ON qr_login_sessions USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE qr_login_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE qr_login_sessions FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_stepup_challenges_org_scope ON stepup_challenges USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE stepup_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE stepup_challenges FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_user_consents_org_scope ON user_consents USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE user_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_consents FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_user_invitations_org_scope ON user_invitations USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE user_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_invitations FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_user_sessions_org_scope ON user_sessions USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_group_memberships_org_scope ON group_memberships USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE group_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_memberships FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_user_application_assignments_org_scope ON user_application_assignments USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE user_application_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_application_assignments FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_backup_codes_org_scope ON mfa_backup_codes USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE mfa_backup_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE mfa_backup_codes FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_policies_org_scope ON mfa_policies USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE mfa_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE mfa_policies FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_push_challenges_org_scope ON mfa_push_challenges USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE mfa_push_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE mfa_push_challenges FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_push_devices_org_scope ON mfa_push_devices USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE mfa_push_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE mfa_push_devices FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_totp_org_scope ON mfa_totp USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE mfa_totp ENABLE ROW LEVEL SECURITY;
ALTER TABLE mfa_totp FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_webauthn_org_scope ON mfa_webauthn USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE mfa_webauthn ENABLE ROW LEVEL SECURITY;
ALTER TABLE mfa_webauthn FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_user_mfa_policies_org_scope ON user_mfa_policies USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE user_mfa_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_mfa_policies FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_oauth_access_tokens_org_scope ON oauth_access_tokens USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE oauth_access_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_access_tokens FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_oauth_authorization_codes_org_scope ON oauth_authorization_codes USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE oauth_authorization_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_authorization_codes FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_oauth_refresh_tokens_org_scope ON oauth_refresh_tokens USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE oauth_refresh_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_refresh_tokens FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_composite_roles_org_scope ON composite_roles USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE composite_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE composite_roles FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_role_permissions_org_scope ON role_permissions USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_user_roles_org_scope ON user_roles USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_application_sso_settings_org_scope ON application_sso_settings USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE application_sso_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_sso_settings FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_group_join_requests_org_scope ON group_join_requests USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE group_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_join_requests FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_access_request_approvals_org_scope ON access_request_approvals USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE access_request_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_request_approvals FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_approval_policies_org_scope ON approval_policies USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE approval_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE approval_policies FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_compliance_reports_org_scope ON compliance_reports USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE compliance_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_reports FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_review_items_org_scope ON review_items USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE review_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_items FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_directory_integrations_org_scope ON directory_integrations USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE directory_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE directory_integrations FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_directory_sync_logs_org_scope ON directory_sync_logs USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE directory_sync_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE directory_sync_logs FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_directory_sync_state_org_scope ON directory_sync_state USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE directory_sync_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE directory_sync_state FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_identity_providers_org_scope ON identity_providers USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE identity_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity_providers FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_data_subject_requests_org_scope ON data_subject_requests USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE data_subject_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_subject_requests FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_privacy_assessments_org_scope ON privacy_assessments USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE privacy_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE privacy_assessments FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_privacy_retention_policies_org_scope ON privacy_retention_policies USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE privacy_retention_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE privacy_retention_policies FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_provisioning_rules_org_scope ON provisioning_rules USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE provisioning_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE provisioning_rules FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_scim_groups_org_scope ON scim_groups USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE scim_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE scim_groups FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_scim_users_org_scope ON scim_users USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE scim_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE scim_users FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_credential_rotations_org_scope ON credential_rotations USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE credential_rotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE credential_rotations FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_device_posture_results_org_scope ON device_posture_results USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE device_posture_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_posture_results FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_posture_checks_org_scope ON posture_checks USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE posture_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE posture_checks FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_policy_rules_org_scope ON policy_rules USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE policy_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE policy_rules FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_webhook_deliveries_org_scope ON webhook_deliveries USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE webhook_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_deliveries FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_proxy_routes_org_scope ON proxy_routes USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE proxy_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE proxy_routes FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_proxy_sessions_org_scope ON proxy_sessions USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE proxy_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE proxy_sessions FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_ziti_certificates_org_scope ON ziti_certificates USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE ziti_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE ziti_certificates FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_ziti_identities_org_scope ON ziti_identities USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE ziti_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE ziti_identities FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_ziti_service_policies_org_scope ON ziti_service_policies USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE ziti_service_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE ziti_service_policies FORCE ROW LEVEL SECURITY;
ALTER POLICY pol_ziti_services_org_scope ON ziti_services USING (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) WITH CHECK (current_setting('app.bypass_rls', true) = 'on' OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);
ALTER TABLE ziti_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE ziti_services FORCE ROW LEVEL SECURITY;
`

var rlsActivateDown = `-- Migration 037 down: revert to dormant permissive policies + RLS off.
ALTER TABLE ziti_services NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ziti_services DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_ziti_services_org_scope ON ziti_services USING (true) WITH CHECK (true);
ALTER TABLE ziti_service_policies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ziti_service_policies DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_ziti_service_policies_org_scope ON ziti_service_policies USING (true) WITH CHECK (true);
ALTER TABLE ziti_identities NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ziti_identities DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_ziti_identities_org_scope ON ziti_identities USING (true) WITH CHECK (true);
ALTER TABLE ziti_certificates NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ziti_certificates DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_ziti_certificates_org_scope ON ziti_certificates USING (true) WITH CHECK (true);
ALTER TABLE proxy_sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE proxy_sessions DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_proxy_sessions_org_scope ON proxy_sessions USING (true) WITH CHECK (true);
ALTER TABLE proxy_routes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE proxy_routes DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_proxy_routes_org_scope ON proxy_routes USING (true) WITH CHECK (true);
ALTER TABLE webhook_deliveries NO FORCE ROW LEVEL SECURITY;
ALTER TABLE webhook_deliveries DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_webhook_deliveries_org_scope ON webhook_deliveries USING (true) WITH CHECK (true);
ALTER TABLE policy_rules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE policy_rules DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_policy_rules_org_scope ON policy_rules USING (true) WITH CHECK (true);
ALTER TABLE posture_checks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE posture_checks DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_posture_checks_org_scope ON posture_checks USING (true) WITH CHECK (true);
ALTER TABLE device_posture_results NO FORCE ROW LEVEL SECURITY;
ALTER TABLE device_posture_results DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_device_posture_results_org_scope ON device_posture_results USING (true) WITH CHECK (true);
ALTER TABLE credential_rotations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE credential_rotations DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_credential_rotations_org_scope ON credential_rotations USING (true) WITH CHECK (true);
ALTER TABLE scim_users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE scim_users DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_scim_users_org_scope ON scim_users USING (true) WITH CHECK (true);
ALTER TABLE scim_groups NO FORCE ROW LEVEL SECURITY;
ALTER TABLE scim_groups DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_scim_groups_org_scope ON scim_groups USING (true) WITH CHECK (true);
ALTER TABLE provisioning_rules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE provisioning_rules DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_provisioning_rules_org_scope ON provisioning_rules USING (true) WITH CHECK (true);
ALTER TABLE privacy_retention_policies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE privacy_retention_policies DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_privacy_retention_policies_org_scope ON privacy_retention_policies USING (true) WITH CHECK (true);
ALTER TABLE privacy_assessments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE privacy_assessments DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_privacy_assessments_org_scope ON privacy_assessments USING (true) WITH CHECK (true);
ALTER TABLE data_subject_requests NO FORCE ROW LEVEL SECURITY;
ALTER TABLE data_subject_requests DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_data_subject_requests_org_scope ON data_subject_requests USING (true) WITH CHECK (true);
ALTER TABLE identity_providers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE identity_providers DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_identity_providers_org_scope ON identity_providers USING (true) WITH CHECK (true);
ALTER TABLE directory_sync_state NO FORCE ROW LEVEL SECURITY;
ALTER TABLE directory_sync_state DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_directory_sync_state_org_scope ON directory_sync_state USING (true) WITH CHECK (true);
ALTER TABLE directory_sync_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE directory_sync_logs DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_directory_sync_logs_org_scope ON directory_sync_logs USING (true) WITH CHECK (true);
ALTER TABLE directory_integrations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE directory_integrations DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_directory_integrations_org_scope ON directory_integrations USING (true) WITH CHECK (true);
ALTER TABLE review_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE review_items DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_review_items_org_scope ON review_items USING (true) WITH CHECK (true);
ALTER TABLE compliance_reports NO FORCE ROW LEVEL SECURITY;
ALTER TABLE compliance_reports DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_compliance_reports_org_scope ON compliance_reports USING (true) WITH CHECK (true);
ALTER TABLE approval_policies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE approval_policies DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_approval_policies_org_scope ON approval_policies USING (true) WITH CHECK (true);
ALTER TABLE access_request_approvals NO FORCE ROW LEVEL SECURITY;
ALTER TABLE access_request_approvals DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_access_request_approvals_org_scope ON access_request_approvals USING (true) WITH CHECK (true);
ALTER TABLE group_join_requests NO FORCE ROW LEVEL SECURITY;
ALTER TABLE group_join_requests DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_group_join_requests_org_scope ON group_join_requests USING (true) WITH CHECK (true);
ALTER TABLE application_sso_settings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE application_sso_settings DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_application_sso_settings_org_scope ON application_sso_settings USING (true) WITH CHECK (true);
ALTER TABLE user_roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_roles DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_user_roles_org_scope ON user_roles USING (true) WITH CHECK (true);
ALTER TABLE role_permissions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE role_permissions DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_role_permissions_org_scope ON role_permissions USING (true) WITH CHECK (true);
ALTER TABLE composite_roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE composite_roles DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_composite_roles_org_scope ON composite_roles USING (true) WITH CHECK (true);
ALTER TABLE oauth_refresh_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE oauth_refresh_tokens DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_oauth_refresh_tokens_org_scope ON oauth_refresh_tokens USING (true) WITH CHECK (true);
ALTER TABLE oauth_authorization_codes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE oauth_authorization_codes DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_oauth_authorization_codes_org_scope ON oauth_authorization_codes USING (true) WITH CHECK (true);
ALTER TABLE oauth_access_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE oauth_access_tokens DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_oauth_access_tokens_org_scope ON oauth_access_tokens USING (true) WITH CHECK (true);
ALTER TABLE user_mfa_policies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_mfa_policies DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_user_mfa_policies_org_scope ON user_mfa_policies USING (true) WITH CHECK (true);
ALTER TABLE mfa_webauthn NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mfa_webauthn DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_webauthn_org_scope ON mfa_webauthn USING (true) WITH CHECK (true);
ALTER TABLE mfa_totp NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mfa_totp DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_totp_org_scope ON mfa_totp USING (true) WITH CHECK (true);
ALTER TABLE mfa_push_devices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mfa_push_devices DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_push_devices_org_scope ON mfa_push_devices USING (true) WITH CHECK (true);
ALTER TABLE mfa_push_challenges NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mfa_push_challenges DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_push_challenges_org_scope ON mfa_push_challenges USING (true) WITH CHECK (true);
ALTER TABLE mfa_policies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mfa_policies DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_policies_org_scope ON mfa_policies USING (true) WITH CHECK (true);
ALTER TABLE mfa_backup_codes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mfa_backup_codes DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_mfa_backup_codes_org_scope ON mfa_backup_codes USING (true) WITH CHECK (true);
ALTER TABLE user_application_assignments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_application_assignments DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_user_application_assignments_org_scope ON user_application_assignments USING (true) WITH CHECK (true);
ALTER TABLE group_memberships NO FORCE ROW LEVEL SECURITY;
ALTER TABLE group_memberships DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_group_memberships_org_scope ON group_memberships USING (true) WITH CHECK (true);
ALTER TABLE user_sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_sessions DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_user_sessions_org_scope ON user_sessions USING (true) WITH CHECK (true);
ALTER TABLE user_invitations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_invitations DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_user_invitations_org_scope ON user_invitations USING (true) WITH CHECK (true);
ALTER TABLE user_consents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE user_consents DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_user_consents_org_scope ON user_consents USING (true) WITH CHECK (true);
ALTER TABLE stepup_challenges NO FORCE ROW LEVEL SECURITY;
ALTER TABLE stepup_challenges DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_stepup_challenges_org_scope ON stepup_challenges USING (true) WITH CHECK (true);
ALTER TABLE qr_login_sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE qr_login_sessions DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_qr_login_sessions_org_scope ON qr_login_sessions USING (true) WITH CHECK (true);
ALTER TABLE password_reset_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_password_reset_tokens_org_scope ON password_reset_tokens USING (true) WITH CHECK (true);
ALTER TABLE password_history NO FORCE ROW LEVEL SECURITY;
ALTER TABLE password_history DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_password_history_org_scope ON password_history USING (true) WITH CHECK (true);
ALTER TABLE notification_preferences NO FORCE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_notification_preferences_org_scope ON notification_preferences USING (true) WITH CHECK (true);
ALTER TABLE login_history NO FORCE ROW LEVEL SECURITY;
ALTER TABLE login_history DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_login_history_org_scope ON login_history USING (true) WITH CHECK (true);
ALTER TABLE known_devices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE known_devices DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_known_devices_org_scope ON known_devices USING (true) WITH CHECK (true);
ALTER TABLE email_verification_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE email_verification_tokens DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_email_verification_tokens_org_scope ON email_verification_tokens USING (true) WITH CHECK (true);
ALTER TABLE api_keys NO FORCE ROW LEVEL SECURITY;
ALTER TABLE api_keys DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_api_keys_org_scope ON api_keys USING (true) WITH CHECK (true);
ALTER TABLE notifications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_notifications_org_scope ON notifications USING (true) WITH CHECK (true);
ALTER TABLE security_alerts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE security_alerts DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_security_alerts_org_scope ON security_alerts USING (true) WITH CHECK (true);
ALTER TABLE access_requests NO FORCE ROW LEVEL SECURITY;
ALTER TABLE access_requests DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_access_requests_org_scope ON access_requests USING (true) WITH CHECK (true);
ALTER TABLE webhook_subscriptions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE webhook_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_webhook_subscriptions_org_scope ON webhook_subscriptions USING (true) WITH CHECK (true);
ALTER TABLE service_accounts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE service_accounts DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_service_accounts_org_scope ON service_accounts USING (true) WITH CHECK (true);
ALTER TABLE access_reviews NO FORCE ROW LEVEL SECURITY;
ALTER TABLE access_reviews DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_access_reviews_org_scope ON access_reviews USING (true) WITH CHECK (true);
ALTER TABLE policies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE policies DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_policies_org_scope ON policies USING (true) WITH CHECK (true);
ALTER TABLE sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_sessions_org_scope ON sessions USING (true) WITH CHECK (true);
ALTER TABLE audit_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_events DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_audit_events_org_scope ON audit_events USING (true) WITH CHECK (true);
ALTER TABLE oauth_clients NO FORCE ROW LEVEL SECURITY;
ALTER TABLE oauth_clients DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_oauth_clients_org_scope ON oauth_clients USING (true) WITH CHECK (true);
ALTER TABLE applications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE applications DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_applications_org_scope ON applications USING (true) WITH CHECK (true);
ALTER TABLE roles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE roles DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_roles_org_scope ON roles USING (true) WITH CHECK (true);
ALTER TABLE groups NO FORCE ROW LEVEL SECURITY;
ALTER TABLE groups DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_groups_org_scope ON groups USING (true) WITH CHECK (true);
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER POLICY pol_users_org_scope ON users USING (true) WITH CHECK (true);
`
