#!/bin/bash
# BrowZer bootstrapper entrypoint wrapper.
# Watches /shared-config/config.json for changes and gracefully restarts
# the node process when the targets configuration is updated.
# This allows dynamic BrowZer target management without container restarts.
#
# The config.json is generated by the access-service and contains:
# { "ZITI_BROWZER_BOOTSTRAPPER_TARGETS": "{\"targetArray\":[...]}" }
#
# Since nconf gives env vars higher priority than config files, we read
# the targets from config.json and export them as env vars before starting node.

set -e

CONFIG_FILE="/shared-config/config.json"
POLL_INTERVAL=5
NODE_PID=""

# Forward SIGTERM to the node process for clean shutdown
cleanup() {
    echo "[entrypoint] Received shutdown signal"
    if [ -n "$NODE_PID" ] && kill -0 "$NODE_PID" 2>/dev/null; then
        kill -TERM "$NODE_PID"
        wait "$NODE_PID" 2>/dev/null
    fi
    exit 0
}
trap cleanup TERM INT

# Load targets from config file into env var (overrides docker-compose default)
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        # Extract the ZITI_BROWZER_BOOTSTRAPPER_TARGETS value from config.json
        # The file format is: {"ZITI_BROWZER_BOOTSTRAPPER_TARGETS": "<json-string>"}
        TARGETS=$(node -e "
            try {
                const cfg = require('$CONFIG_FILE');
                if (cfg.ZITI_BROWZER_BOOTSTRAPPER_TARGETS) {
                    process.stdout.write(cfg.ZITI_BROWZER_BOOTSTRAPPER_TARGETS);
                }
            } catch(e) {}
        " 2>/dev/null)
        if [ -n "$TARGETS" ]; then
            export ZITI_BROWZER_BOOTSTRAPPER_TARGETS="$TARGETS"
            echo "[entrypoint] Loaded targets from config file"
        fi

        # Also load HOST override if present in config
        HOST_OVERRIDE=$(node -e "
            try {
                const cfg = require('$CONFIG_FILE');
                if (cfg.ZITI_BROWZER_BOOTSTRAPPER_HOST) {
                    process.stdout.write(cfg.ZITI_BROWZER_BOOTSTRAPPER_HOST);
                }
            } catch(e) {}
        " 2>/dev/null)
        if [ -n "$HOST_OVERRIDE" ]; then
            export ZITI_BROWZER_BOOTSTRAPPER_HOST="$HOST_OVERRIDE"
            echo "[entrypoint] Loaded HOST override: $HOST_OVERRIDE"
        fi

        if [ -n "$TARGETS" ]; then
            return 0
        fi
    fi
    echo "[entrypoint] Using default targets from env var"
    return 1
}

LISTEN_PORT="${ZITI_BROWZER_BOOTSTRAPPER_LISTEN_PORT:-8445}"

# port_free: succeeds (0) when LISTEN_PORT is bindable, fails (1) when in use.
# Only bash + node are present in this image (no ss/lsof/fuser), so probe with
# node by attempting a throwaway listen.
port_free() {
    node -e "const n=require('net');const s=n.createServer();s.once('error',()=>process.exit(1));s.once('listening',()=>s.close(()=>process.exit(0)));s.listen(${LISTEN_PORT},'0.0.0.0')" 2>/dev/null
}

# kill_stray_node: last-resort cleanup of orphaned bootstrapper processes that
# still hold the port (e.g. a restart whose PID we lost track of). Scans /proc
# since pkill isn't available. Never targets this shell.
kill_stray_node() {
    for d in /proc/[0-9]*; do
        pid="${d##*/}"
        [ "$pid" = "$$" ] && continue
        if [ "$(cat "$d/comm" 2>/dev/null)" = "node" ]; then
            echo "[entrypoint] killing stray node pid $pid holding :$LISTEN_PORT"
            kill -9 "$pid" 2>/dev/null || true
        fi
    done
}

# wait_for_port_free: block until LISTEN_PORT is released, so we never launch a
# new node while the previous one (or an orphan) still holds it — that was the
# EADDRINUSE crash-loop. After a grace period, forcibly clear any stray holder.
wait_for_port_free() {
    local n=0
    while ! port_free; do
        n=$((n + 1))
        if [ "$n" -gt 20 ]; then
            echo "[entrypoint] :$LISTEN_PORT still busy after ${n}s"
            kill_stray_node
            sleep 2
            return 0
        fi
        sleep 1
    done
    return 0
}

start_node() {
    load_config || true
    wait_for_port_free
    echo "[entrypoint] Starting bootstrapper..."
    cd /home/node/ziti-browzer-bootstrapper && node index.js &
    NODE_PID=$!
    echo "[entrypoint] Bootstrapper started with PID $NODE_PID"
}

# stop_node: terminate the bootstrapper and wait until the port is actually
# free. node forks a child that holds the listening socket, so killing only the
# tracked NODE_PID (the parent) leaves the child holding :LISTEN_PORT — that was
# the EADDRINUSE crash-loop. We TERM the parent for a graceful shutdown, then
# sweep any remaining node procs (this container runs only the bootstrapper).
stop_node() {
    if [ -n "$NODE_PID" ] && kill -0 "$NODE_PID" 2>/dev/null; then
        kill -TERM "$NODE_PID" 2>/dev/null || true
        WAIT_COUNT=0
        while kill -0 "$NODE_PID" 2>/dev/null && [ $WAIT_COUNT -lt 10 ]; do
            sleep 1
            WAIT_COUNT=$((WAIT_COUNT + 1))
        done
        wait "$NODE_PID" 2>/dev/null || true
    fi
    # Reap the listener child (and any orphan) so the port frees immediately.
    if ! port_free; then
        kill_stray_node
    fi
}

restart_node() {
    echo "[entrypoint] Restarting bootstrapper due to config change..."
    stop_node
    # start_node blocks on wait_for_port_free, so we never race the old listener.
    start_node
}

# Wait briefly for config file (access-service may not have written it yet)
echo "[entrypoint] Checking for config file at $CONFIG_FILE..."
WAIT_ATTEMPTS=0
while [ ! -f "$CONFIG_FILE" ] && [ $WAIT_ATTEMPTS -lt 30 ]; do
    sleep 2
    WAIT_ATTEMPTS=$((WAIT_ATTEMPTS + 1))
done

if [ -f "$CONFIG_FILE" ]; then
    echo "[entrypoint] Config file found"
else
    echo "[entrypoint] Config file not found after 60s, using env var fallback"
fi

# Start the bootstrapper
start_node

# Get initial mtime (0 if file doesn't exist)
LAST_MTIME=$(stat -c %Y "$CONFIG_FILE" 2>/dev/null || echo "0")

# Poll for config changes
while true; do
    sleep $POLL_INTERVAL

    # Check if node process crashed
    if ! kill -0 "$NODE_PID" 2>/dev/null; then
        echo "[entrypoint] Node process died unexpectedly, restarting..."
        # start_node waits for the port to free before relaunching, so a
        # lingering listener can't trigger an EADDRINUSE crash-loop.
        start_node
        continue
    fi

    # Check for config file changes
    CURR_MTIME=$(stat -c %Y "$CONFIG_FILE" 2>/dev/null || echo "0")
    if [ "$CURR_MTIME" != "$LAST_MTIME" ] && [ "$CURR_MTIME" != "0" ]; then
        echo "[entrypoint] Config file changed (mtime: $LAST_MTIME -> $CURR_MTIME)"
        # Settle delay: lets a burst of successive writes (e.g. several feature
        # toggles) finish, then adopt the latest mtime so they coalesce into a
        # single restart instead of a restart storm.
        sleep 1
        LAST_MTIME=$(stat -c %Y "$CONFIG_FILE" 2>/dev/null || echo "$CURR_MTIME")
        restart_node
    fi
done
