openapi: 3.0.3
info:
  title: OpenIDX Notifications Service
  description: User notification management and preferences.
  version: 0.1.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost:8001
    description: Local development (hosted inside identity-service)

security:
  - bearerAuth: []

tags:
  - name: Notifications

paths:
  /api/v1/identity/notifications:
    get:
      tags: [Notifications]
      summary: List user notifications
      operationId: listNotifications
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 20
        - name: unread_only
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Paginated list of notifications
          headers:
            X-Total-Count:
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/identity/notifications/unread-count:
    get:
      tags: [Notifications]
      summary: Get unread notification count
      operationId: getUnreadNotificationCount
      responses:
        '200':
          description: Unread count
          content:
            application/json:
              schema:
                type: object
                properties:
                  unread_count:
                    type: integer
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/identity/notifications/mark-read:
    post:
      tags: [Notifications]
      summary: Mark notifications as read
      operationId: markNotificationsRead
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [notification_ids]
              properties:
                notification_ids:
                  type: array
                  items:
                    type: string
                    format: uuid
      responses:
        '200':
          description: Notifications marked as read
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/identity/notifications/mark-all-read:
    post:
      tags: [Notifications]
      summary: Mark all notifications as read
      operationId: markAllNotificationsRead
      responses:
        '200':
          description: All notifications marked as read
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/identity/notifications/preferences:
    get:
      tags: [Notifications]
      summary: Get notification preferences
      operationId: getNotificationPreferences
      responses:
        '200':
          description: Notification preferences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPreferences'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags: [Notifications]
      summary: Update notification preferences
      operationId: updateNotificationPreferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationPreferences'
      responses:
        '200':
          description: Preferences updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPreferences'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        status:
          type: integer

    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        type:
          type: string
          enum: [info, warning, error, success]
        title:
          type: string
        message:
          type: string
        read:
          type: boolean
        link:
          type: string
        created_at:
          type: string
          format: date-time

    NotificationPreferences:
      type: object
      properties:
        email_enabled:
          type: boolean
        push_enabled:
          type: boolean
        security_alerts:
          type: boolean
        access_reviews:
          type: boolean
        system_updates:
          type: boolean
        group_changes:
          type: boolean
        login_alerts:
          type: boolean
