#!/usr/bin/env bash
#
# check-third-party-notices.sh — THIRD_PARTY_NOTICES.md is derived, not written.
#
# WHY THIS EXISTS. NOTICE says the Go modules compiled into the OpenIDX
# binaries are listed, with their licences, in THIRD_PARTY_NOTICES.md. A list
# kept by hand is true on the day it is written and silently wrong after the
# first `go get`; a list nothing checks is the shape this repository refuses —
# a control that reports success while the thing it exists to make true is not
# true. So the file is generated from the module graph by go-licenses, and this
# script, run in CI, fails when the committed file differs from a fresh
# generation.
#
# Measured on 2026-09-19, before this existed: the License Compliance job ran
# go-licenses behind `|| echo` and continue-on-error, its npm half ran a
# command that printed usage and wrote no file, and its summary said "License
# reports generated for Go and NPM dependencies" either way. Nothing in the
# repository named a single third-party licence.
#
# VERSIONS ARE LEFT OUT on purpose. The list names module path and licence,
# not the version, so bumping a dependency does not stale the file; adding,
# removing or relicensing one does, and that is the change a human should see.
#
# Usage:
#   scripts/check-third-party-notices.sh          # a fresh generation must equal the committed file
#   scripts/check-third-party-notices.sh --write  # regenerate in place
# Environment, for the self-test: GO_LICENSES=<binary>  NOTICES_FILE=<path>
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
OUT="${NOTICES_FILE:-THIRD_PARTY_NOTICES.md}"
MODE=check
case "${1:-}" in
	--write) MODE=write ;;
	"") ;;
	*) echo "usage: $0 [--write]" >&2; exit 2 ;;
esac

# go-licenses: the one on PATH, the one `go install` leaves in GOPATH/bin, or a
# pinned `go run` (which touches neither go.mod nor go.sum). A missing tool is
# a failure with a message, never a pass.
if [ -n "${GO_LICENSES:-}" ]; then
	GL=("$GO_LICENSES")
elif command -v go-licenses >/dev/null 2>&1; then
	GL=(go-licenses)
elif [ -x "$(go env GOPATH 2>/dev/null)/bin/go-licenses" ]; then
	GL=("$(go env GOPATH)/bin/go-licenses")
else
	GL=(go run github.com/google/go-licenses@v1.6.0)
fi

# go-licenses resolves the standard library through GOROOT. When the go
# command has switched to a downloaded toolchain (GOTOOLCHAIN=auto with a
# go.mod newer than the installed go), GOROOT is not in the environment and
# the tool reports every std package as "does not have module info" and dies.
# Asking the go command is what makes the run work on such a machine.
GOROOT="$(go env GOROOT)"
export GOROOT

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if ! "${GL[@]}" report ./... >"$WORK/report.csv" 2>"$WORK/report.err"; then
	echo "check-third-party-notices: go-licenses report failed:" >&2
	grep -v '^W[0-9]' "$WORK/report.err" | tail -n 20 >&2
	exit 2
fi
if [ ! -s "$WORK/report.csv" ]; then
	echo "check-third-party-notices: go-licenses reported no modules at all. That is not a clean bill; it is a tool that answered nothing." >&2
	exit 2
fi

python3 - "$WORK/report.csv" "$WORK/new.md" "$WORK/count" <<'PY'
import csv, sys
from collections import Counter

OWN = "github.com/openidx/openidx"
rows = {}
for rec in csv.reader(open(sys.argv[1])):
    if len(rec) != 3:
        continue
    mod, _url, lic = rec
    # Ourselves, and Go files that ship inside node_modules under our path.
    if mod == OWN or mod.startswith(OWN + "/"):
        continue
    rows[mod] = lic
if not rows:
    sys.exit("check-third-party-notices: every reported module was our own; the report is not what this script expects")
counts = Counter(rows.values())

out = []
out.append("# Third-party notices")
out.append("")
out.append("<!-- GENERATED by `scripts/check-third-party-notices.sh --write` from the Go module")
out.append("     graph (`go-licenses report ./...`). Do not edit by hand: the License Compliance")
out.append("     job in .github/workflows/security-scan.yml fails when this file differs from a")
out.append("     fresh generation. Versions are deliberately absent; see the script's header. -->")
out.append("")
out.append("The Go modules and packages compiled into the OpenIDX binaries, with the licence")
out.append("[go-licenses](https://github.com/google/go-licenses) identifies for each. Versions")
out.append("are in `go.sum`; this list names what ships and under which terms. Each entry links")
out.append("to the module's licence page on pkg.go.dev. The admin console's npm dependencies")
out.append("are reported by the same CI job as the `npm-licenses` artifact and are not listed here.")
out.append("")
out.append("## Summary")
out.append("")
out.append("| Licence | Count |")
out.append("|---------|-------|")
for lic, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
    out.append(f"| {lic} | {n} |")
out.append(f"| **Total** | **{len(rows)}** |")
out.append("")
out.append("## Modules and packages")
out.append("")
out.append("| Module or package | Licence |")
out.append("|-------------------|---------|")
for mod in sorted(rows):
    out.append(f"| [{mod}](https://pkg.go.dev/{mod}?tab=licenses) | {rows[mod]} |")
out.append("")
open(sys.argv[2], "w").write("\n".join(out))
open(sys.argv[3], "w").write(str(len(rows)))
PY
rc=$?
if [ "$rc" -ne 0 ]; then exit 2; fi
n="$(cat "$WORK/count")"

if [ "$MODE" = write ]; then
	cp "$WORK/new.md" "$OUT"
	echo "check-third-party-notices: wrote $OUT ($n third-party entries)"
	exit 0
fi

if [ ! -f "$OUT" ]; then
	echo "check-third-party-notices: $OUT does not exist. Generate it: bash scripts/check-third-party-notices.sh --write" >&2
	exit 1
fi
if ! diff -u "$OUT" "$WORK/new.md" >"$WORK/diff"; then
	echo "check-third-party-notices: $OUT is stale. The module graph and the committed list differ:" >&2
	head -n 60 "$WORK/diff" >&2
	echo "Regenerate it: bash scripts/check-third-party-notices.sh --write" >&2
	exit 1
fi
echo "check-third-party-notices: ok — $OUT matches the module graph ($n third-party entries)"
