#!/usr/bin/env bash
# generate-secrets.sh — Generate a .env file with cryptographically random secrets.
# Usage: ./scripts/generate-secrets.sh [output-file]
#
# If output-file is omitted, writes to .env in the repository root.
# Existing .env files are backed up to .env.bak before overwriting.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="${1:-$REPO_ROOT/.env}"

# --- helpers ---
rand_password() {
  # 32-character base64url string (no special chars that break connection strings)
  LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
}

rand_hex() {
  # 32-byte hex string (64 hex chars)
  LC_ALL=C tr -dc 'a-f0-9' </dev/urandom | head -c 64
}

rand_key_32() {
  # Exactly 32 printable ASCII characters (for AES-256)
  LC_ALL=C tr -dc 'A-Za-z0-9!@#%^&*_+=' </dev/urandom | head -c 32
}

# --- generate values ---
POSTGRES_PASSWORD="$(rand_password)"
REDIS_PASSWORD="$(rand_password)"
KEYCLOAK_ADMIN_PASSWORD="$(rand_password)"
JWT_SECRET="$(rand_hex)"
ENCRYPTION_KEY="$(rand_key_32)"
GRAFANA_ADMIN_PASSWORD="$(rand_password)"

# --- backup existing file ---
if [ -f "$OUTPUT" ]; then
  cp "$OUTPUT" "${OUTPUT}.bak"
  echo "Backed up existing $OUTPUT to ${OUTPUT}.bak"
fi

# --- write .env ---
cat > "$OUTPUT" <<EOF
# OpenIDX Environment Configuration
# Generated by scripts/generate-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file to version control.

# ----- Environment -----
APP_ENV=development
LOG_LEVEL=debug

# ----- Database -----
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgres://openidx:${POSTGRES_PASSWORD}@localhost:5432/openidx?sslmode=disable

# ----- Redis -----
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379

# ----- Elasticsearch -----
ELASTICSEARCH_URL=http://localhost:9200

# ----- Keycloak -----
KEYCLOAK_URL=http://localhost:8180
KEYCLOAK_REALM=openidx
KEYCLOAK_CLIENT_ID=openidx-api
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

# ----- OPA -----
OPA_URL=http://localhost:8281

# ----- Security -----
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ----- OAuth / OIDC -----
OAUTH_ISSUER=http://localhost:8006
OAUTH_JWKS_URL=http://oauth-service:8006/.well-known/jwks.json

# ----- Frontend -----
VITE_API_URL=http://localhost:8088
VITE_OAUTH_URL=http://localhost:8006
VITE_OAUTH_CLIENT_ID=admin-console
VITE_AUTH_PROVIDER=openidx

# ----- Observability -----
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

# ----- SMTP (optional) -----
SMTP_HOST=
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM=noreply@openidx.io
EOF

echo "Generated $OUTPUT with random secrets."
echo ""
echo "Secrets summary:"
echo "  POSTGRES_PASSWORD  = ${POSTGRES_PASSWORD:0:8}..."
echo "  REDIS_PASSWORD     = ${REDIS_PASSWORD:0:8}..."
echo "  KEYCLOAK_ADMIN_PW  = ${KEYCLOAK_ADMIN_PASSWORD:0:8}..."
echo "  JWT_SECRET         = ${JWT_SECRET:0:8}..."
echo "  ENCRYPTION_KEY     = ${ENCRYPTION_KEY:0:8}..."
echo "  GRAFANA_ADMIN_PW   = ${GRAFANA_ADMIN_PASSWORD:0:8}..."
