apisix:
  data_encryption:
    enable: false
  node_listen: 9081
  enable_http2: true
  enable_ipv6: false

  ssl:
    enable: true
    listen:
      - port: 9444
      - port: 443
    ssl_protocols: TLSv1.2 TLSv1.3

nginx_config:
  worker_processes: auto
  event:
    worker_connections: 10620
  error_log: "logs/error.log"
  http:
    access_log: "logs/access.log"
    real_ip_header: X-Forwarded-For
    real_ip_recursive: "on"
    send_timeout: 600s
    proxy_send_timeout: 600s
    proxy_read_timeout: 600s
    keepalive_timeout: 360s

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_listen:
      ip: 0.0.0.0
      port: 9280
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: CHANGE_ME_ADMIN_KEY
        role: admin
  etcd:
    host:
      - "http://127.0.0.1:2379"
    prefix: "/apisix-oidx"
    timeout: 30
