// zeroanswer finds aggregate queries whose failure is reported as a number.
//
// THE DEFECT. A one-row aggregate -- COUNT, SUM, AVG, MIN, MAX, EXISTS -- always
// returns exactly one row. So this:
//
//	s.db.Pool.QueryRow(ctx, `SELECT COUNT(*) FROM users WHERE org_id = $1`,
//	    org.ID).Scan(&totalUsers)
//
// can never fail because "there is no data". It fails because the query did not
// run: a column that is not there, a policy that refused, a connection that
// died, an org_id that did not parse. The destination keeps its zero, and the
// caller reads that zero as an answer -- prints it on a dashboard, puts it in a
// compliance report, divides by it, decides a control passed.
//
// COUNT over no rows is also 0, and in the destination the two are identical.
// Only the error told them apart, and it was thrown away.
//
// This is not a style rule about unchecked errors. It is narrow on purpose: it
// fires only on a literal SQL statement whose SELECT list is an aggregate, read
// through QueryRow into a destination, with the error discarded. A row lookup
// where "no rows" is a legitimate answer is counted and reported but is NOT a
// finding, because there the zero value can be the right reading -- a guard that
// fires on correct code is one somebody turns off.
//
// Usage:
//
//	go run ./tools/zeroanswer [-fail] [-census] [dir ...]
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type finding struct {
	key  string // file + hash of the normalized statement
	file string
	line int
	fn   string // the function holding it, which is what reads the zero
	dest string
	sql  string
}

// aggregateSelect matches a SELECT whose first output column is an aggregate.
// COALESCE(COUNT(...), 0) and COUNT(DISTINCT x) are the two wrappings this tree
// actually uses; both are still one row.
var aggregateSelect = regexp.MustCompile(
	`(?is)^\s*SELECT\s+(COALESCE\s*\(\s*)?(COUNT|SUM|AVG|MIN|MAX|EXISTS)\s*\(`)

func main() {
	fail := flag.Bool("fail", false, "exit non-zero when findings exist that the register does not carry")
	seed := flag.Bool("seed", false, "print register lines for every current finding, to be given verdicts by hand")
	census := flag.Bool("census", false, "print every discarded QueryRow().Scan(), aggregate or not, and exit")
	flag.Parse()

	roots := flag.Args()
	if len(roots) == 0 {
		roots = []string{"internal", "cmd"}
	}

	aggregates, lookups := scan(roots)

	if *seed {
		fmt.Println("// generated by: go run ./tools/zeroanswer -seed")
		for _, f := range aggregates {
			fmt.Printf("\t%q: %q,\n", f.key, fmt.Sprintf("%s:%d %s: %s", f.file, f.line, f.fn, f.dest))
		}
		return
	}

	if *census {
		fmt.Println("aggregate-shaped (one row always, so any error is real):")
		for _, f := range aggregates {
			fmt.Printf("  %s:%d  %s  %s  <- %s\n", f.file, f.line, f.fn, f.dest, f.sql)
		}
		fmt.Println("\nrow lookups (no-row is a legitimate answer; reported, not a finding):")
		for _, f := range lookups {
			fmt.Printf("  %s:%d  %s  <- %s\n", f.file, f.line, f.dest, f.sql)
		}
		return
	}

	var newOnes []finding
	seen := map[string]bool{}
	for _, f := range aggregates {
		seen[f.key] = true
		if _, ok := knownZeroAnswers[f.key]; !ok {
			newOnes = append(newOnes, f)
		}
	}
	var stale []string
	for k := range knownZeroAnswers {
		if !seen[k] {
			stale = append(stale, k)
		}
	}
	sort.Strings(stale)

	for _, f := range newOnes {
		fmt.Printf("%s:%d: %s in %s is set from an aggregate whose error is discarded; "+
			"a failed query leaves it zero and the caller reads that as an answer\n  %s\n",
			f.file, f.line, f.dest, f.fn, f.sql)
	}
	for _, k := range stale {
		fmt.Printf("stale register entry %q: no longer a finding. Delete the line -- "+
			"the register only shrinks.\n", k)
	}

	fmt.Fprintf(os.Stderr,
		"zeroanswer: %d aggregate(s) with a discarded error (%d registered, %d new, %d stale), "+
			"%d row lookup(s) not counted as findings\n",
		len(aggregates), len(knownZeroAnswers), len(newOnes), len(stale), len(lookups))

	if *fail && (len(newOnes) > 0 || len(stale) > 0) {
		os.Exit(1)
	}
}

func scan(roots []string) (aggregates, lookups []finding) {
	fset := token.NewFileSet()
	for _, root := range roots {
		_ = filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() || !strings.HasSuffix(p, ".go") || strings.HasSuffix(p, "_test.go") {
				return nil
			}
			f, err := parser.ParseFile(fset, p, nil, 0)
			if err != nil {
				return nil
			}
			for _, decl := range f.Decls {
				fd, ok := decl.(*ast.FuncDecl)
				if !ok {
					continue
				}
				fnName := fd.Name.Name
				ast.Inspect(fd, func(n ast.Node) bool {
					call := discardedCall(n)
					if call == nil {
						return true
					}
					sel := call.Fun.(*ast.SelectorExpr)
					recv, ok := sel.X.(*ast.CallExpr)
					if !ok {
						return true
					}
					rsel, ok := recv.Fun.(*ast.SelectorExpr)
					if !ok || rsel.Sel.Name != "QueryRow" {
						return true
					}
					sql, literal := statementOf(recv)
					if !literal {
						return true
					}
					pos := fset.Position(call.Pos())
					dest := destOf(call)
					fnd := finding{
						// The destination is part of the key because one file
						// can run the same statement into different variables
						// -- attestation.go asks for its pending count in three
						// handlers -- and those are three separate verdicts.
						key:  fmt.Sprintf("%s#%s", filepath.ToSlash(pos.Filename), hash(sql+"|"+dest)),
						file: filepath.ToSlash(pos.Filename),
						line: pos.Line,
						fn:   fnName,
						dest: dest,
						sql:  short(sql),
					}
					if aggregateSelect.MatchString(sql) {
						aggregates = append(aggregates, fnd)
					} else {
						lookups = append(lookups, fnd)
					}
					return true
				})
			}
			return nil
		})
	}
	sort.Slice(aggregates, func(i, j int) bool { return aggregates[i].key < aggregates[j].key })
	sort.Slice(lookups, func(i, j int) bool { return lookups[i].key < lookups[j].key })
	return aggregates, lookups
}

// discardedCall returns the Scan call when its error is thrown away: either the
// call is a bare statement, or its single result is assigned to the blank
// identifier.
func discardedCall(n ast.Node) *ast.CallExpr {
	var call *ast.CallExpr
	switch s := n.(type) {
	case *ast.ExprStmt:
		c, ok := s.X.(*ast.CallExpr)
		if !ok {
			return nil
		}
		call = c
	case *ast.AssignStmt:
		if len(s.Rhs) != 1 || len(s.Lhs) != 1 {
			return nil
		}
		id, ok := s.Lhs[0].(*ast.Ident)
		if !ok || id.Name != "_" {
			return nil
		}
		c, ok := s.Rhs[0].(*ast.CallExpr)
		if !ok {
			return nil
		}
		call = c
	default:
		return nil
	}
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Scan" {
		return nil
	}
	return call
}

// statementOf returns the first string literal argument -- the SQL -- and
// whether one was found. A statement built at run time is not analysed: its
// shape is not knowable here, and guessing would make the check unsound.
func statementOf(call *ast.CallExpr) (string, bool) {
	for _, a := range call.Args {
		if bl, ok := a.(*ast.BasicLit); ok && bl.Kind == token.STRING {
			return normalize(strings.Trim(bl.Value, "`\"")), true
		}
	}
	return "", false
}

func destOf(call *ast.CallExpr) string {
	if len(call.Args) == 0 {
		return "(no destination)"
	}
	var b strings.Builder
	if err := printExpr(&b, call.Args[0]); err != nil {
		return "?"
	}
	return b.String()
}

func printExpr(b *strings.Builder, e ast.Expr) error {
	switch v := e.(type) {
	case *ast.UnaryExpr:
		b.WriteString("&")
		return printExpr(b, v.X)
	case *ast.Ident:
		b.WriteString(v.Name)
	case *ast.SelectorExpr:
		if err := printExpr(b, v.X); err != nil {
			return err
		}
		b.WriteString("." + v.Sel.Name)
	default:
		b.WriteString("?")
	}
	return nil
}

func normalize(s string) string { return strings.Join(strings.Fields(s), " ") }

func short(s string) string {
	if len(s) > 110 {
		return s[:110] + "…"
	}
	return s
}

func hash(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:])[:12]
}
