// Package identity - Admin-generated MFA Bypass Codes
package identity

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"
	"golang.org/x/crypto/bcrypt"

	"github.com/openidx/openidx/internal/common/orgctx"

	"github.com/openidx/openidx/internal/common/logsafe"
)

// MFABypassCode represents an admin-generated bypass code
type MFABypassCode struct {
	ID             string     `json:"id"`
	UserID         string     `json:"user_id"`
	UserEmail      string     `json:"user_email,omitempty"`
	Code           string     `json:"code,omitempty"` // Only returned on creation
	Reason         string     `json:"reason"`
	GeneratedBy    string     `json:"generated_by"`
	GeneratorEmail string     `json:"generator_email,omitempty"`
	ValidFrom      time.Time  `json:"valid_from"`
	ValidUntil     time.Time  `json:"valid_until"`
	MaxUses        int        `json:"max_uses"`
	UseCount       int        `json:"use_count"`
	Status         string     `json:"status"` // active, used, expired, revoked
	UsedAt         *time.Time `json:"used_at,omitempty"`
	UsedFromIP     string     `json:"used_from_ip,omitempty"`
	RevokedAt      *time.Time `json:"revoked_at,omitempty"`
	RevokedBy      *string    `json:"revoked_by,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
}

// MFABypassAuditEntry represents an audit log entry
type MFABypassAuditEntry struct {
	ID           string                 `json:"id"`
	BypassCodeID *string                `json:"bypass_code_id,omitempty"`
	UserID       *string                `json:"user_id,omitempty"`
	Action       string                 `json:"action"`
	PerformedBy  *string                `json:"performed_by,omitempty"`
	IPAddress    string                 `json:"ip_address,omitempty"`
	UserAgent    string                 `json:"user_agent,omitempty"`
	Details      map[string]interface{} `json:"details,omitempty"`
	CreatedAt    time.Time              `json:"created_at"`
}

// GenerateBypassCodeRequest for creating a bypass code
type GenerateBypassCodeRequest struct {
	UserID     string `json:"user_id"`
	Reason     string `json:"reason"`
	ValidHours int    `json:"valid_hours"` // How long the code is valid (default 24)
	MaxUses    int    `json:"max_uses"`    // Max times code can be used (default 1)
}

// GenerateMFABypassCode creates a new bypass code for a user
func (s *Service) GenerateMFABypassCode(ctx context.Context, req *GenerateBypassCodeRequest, adminID, adminIP string) (*MFABypassCode, error) {
	if req.UserID == "" {
		return nil, errors.New("user_id is required")
	}
	if req.Reason == "" {
		return nil, errors.New("reason is required")
	}

	org, err := orgctx.From(ctx)
	if err != nil {
		return nil, err
	}

	// Verify user exists within the caller's org
	var userEmail string
	err = s.db.Pool.QueryRow(ctx, "SELECT email FROM users WHERE id = $1 AND org_id = $2", req.UserID, org.ID).Scan(&userEmail)
	if err != nil {
		return nil, errors.New("user not found")
	}

	// Generate secure bypass code (16 characters)
	codeBytes := make([]byte, 12)
	if _, err := rand.Read(codeBytes); err != nil {
		return nil, err
	}
	code := base64.URLEncoding.EncodeToString(codeBytes)[:16]

	// Hash the code
	codeHash, err := bcrypt.GenerateFromPassword([]byte(code), bcryptCost)
	if err != nil {
		return nil, err
	}

	// Set defaults
	validHours := req.ValidHours
	if validHours <= 0 {
		validHours = 24
	}
	maxUses := req.MaxUses
	if maxUses <= 0 {
		maxUses = 1
	}

	validFrom := time.Now()
	validUntil := validFrom.Add(time.Duration(validHours) * time.Hour)

	bypassID := uuid.New().String()

	// Create bypass code
	query := `
		INSERT INTO mfa_bypass_codes (
			id, org_id, user_id, code_hash, reason, generated_by,
			valid_from, valid_until, max_uses, use_count, status, created_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 0, 'active', NOW())
		RETURNING created_at
	`

	var createdAt time.Time
	err = s.db.Pool.QueryRow(ctx, query,
		bypassID, org.ID, req.UserID, string(codeHash), req.Reason, adminID,
		validFrom, validUntil, maxUses,
	).Scan(&createdAt)
	if err != nil {
		return nil, err
	}

	// Log audit event
	s.logBypassAudit(ctx, bypassID, req.UserID, "generated", &adminID, adminIP, "", map[string]interface{}{
		"reason":      req.Reason,
		"valid_hours": validHours,
		"max_uses":    maxUses,
	})

	return &MFABypassCode{
		ID:          bypassID,
		UserID:      req.UserID,
		UserEmail:   userEmail,
		Code:        code, // Return plain code only on creation
		Reason:      req.Reason,
		GeneratedBy: adminID,
		ValidFrom:   validFrom,
		ValidUntil:  validUntil,
		MaxUses:     maxUses,
		UseCount:    0,
		Status:      "active",
		CreatedAt:   createdAt,
	}, nil
}

// VerifyBypassCode verifies and uses a bypass code
func (s *Service) VerifyBypassCode(ctx context.Context, userID, code, ipAddress, userAgent string) (bool, error) {
	// The belt is lifted for the whole of this function, its transaction and the
	// audit write that follows it, for the reason set out on
	// VerifyHardwareToken: this runs on the sign-in and step-up paths, whose
	// callers do not all carry a resolved organization, and under FORCE RLS an
	// unset app.org_id turns every code into "no such code". This function has
	// already been broken once in exactly that shape — see the comment below
	// about "conn busy", where the break-glass credential simply never worked
	// and the caller read it as a wrong code.
	//
	// The tenant lives in the predicate instead: `user_id = $1` is the
	// authenticated user and the org term ties the row to that user's own
	// organization, so no other tenant's code can match.
	ctx = orgctx.WithBypassRLS(ctx)

	// Begin a transaction to prevent TOCTOU race between checking and updating bypass codes
	tx, err := s.db.Pool.Begin(ctx)
	if err != nil {
		return false, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Get active bypass codes for user with FOR UPDATE to lock rows
	//orgscope:ignore break-glass verification on a path that may not have resolved an org; scoped by the user's own org_id
	query := `
		SELECT id, code_hash, valid_until, max_uses, use_count
		FROM mfa_bypass_codes
		WHERE user_id = $1 AND status = 'active'
		  AND org_id = (SELECT org_id FROM users WHERE id = $1)
		ORDER BY created_at DESC
		FOR UPDATE
	`

	rows, err := tx.Query(ctx, query, userID)
	if err != nil {
		return false, err
	}

	// Drain and CLOSE before issuing any write.
	//
	// A pgx transaction is pinned to one connection and allows one query on it
	// at a time, so an Exec inside this loop came back "conn busy" and the
	// function returned (false, err) -- for every code, valid or not. Nothing
	// noticed, because the caller reads that as "wrong code": the break-glass
	// credential simply never worked. The rows stay locked by FOR UPDATE until
	// the transaction ends, so collecting first costs nothing.
	type candidate struct {
		id         string
		codeHash   string
		validUntil time.Time
		maxUses    int
		useCount   int
	}
	var candidates []candidate
	for rows.Next() {
		var c candidate
		if err := rows.Scan(&c.id, &c.codeHash, &c.validUntil, &c.maxUses, &c.useCount); err != nil {
			rows.Close()
			return false, err
		}
		candidates = append(candidates, c)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return false, err
	}

	for _, c := range candidates {
		// Check expiration
		if time.Now().After(c.validUntil) {
			if _, err := tx.Exec(ctx,
				//orgscope:ignore id from the org-scoped SELECT above; tx runs on the bypassed verification context
				"UPDATE mfa_bypass_codes SET status = 'expired' WHERE id = $1", c.id); err != nil {
				return false, err
			}
			continue
		}

		// Check max uses
		if c.maxUses > 0 && c.useCount >= c.maxUses {
			if _, err := tx.Exec(ctx,
				//orgscope:ignore id from the org-scoped SELECT above; tx runs on the bypassed verification context
				"UPDATE mfa_bypass_codes SET status = 'used' WHERE id = $1", c.id); err != nil {
				return false, err
			}
			continue
		}

		// Verify code
		if err := bcrypt.CompareHashAndPassword([]byte(c.codeHash), []byte(code)); err != nil {
			continue // Try next code
		}

		// Code is valid - update usage atomically within the transaction
		newUseCount := c.useCount + 1
		newStatus := "active"
		if c.maxUses > 0 && newUseCount >= c.maxUses {
			newStatus = "used"
		}

		_, err = tx.Exec(ctx,
			//orgscope:ignore id from the org-scoped SELECT above; tx runs on the bypassed verification context
			`UPDATE mfa_bypass_codes
			SET use_count = $1, status = $2, used_at = NOW(), used_from_ip = $3
			WHERE id = $4`,
			newUseCount, newStatus, ipAddress, c.id,
		)
		if err != nil {
			return false, err
		}

		// Commit the transaction
		if err := tx.Commit(ctx); err != nil {
			return false, fmt.Errorf("failed to commit transaction: %w", err)
		}

		// Log audit (outside transaction - best effort)
		s.logBypassAudit(ctx, c.id, userID, "used", nil, ipAddress, userAgent, nil)

		return true, nil
	}

	// No matching code found - commit to persist any status updates (expired/used)
	if err := tx.Commit(ctx); err != nil {
		return false, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return false, nil
}

// ListBypassCodes returns bypass codes with filtering
func (s *Service) ListBypassCodes(ctx context.Context, userID, status string, activeOnly bool, limit, offset int) ([]MFABypassCode, int, error) {
	if limit <= 0 {
		limit = 50
	}

	org, err := orgctx.From(ctx)
	if err != nil {
		return nil, 0, err
	}

	// Since v145 the code carries its own org_id, so the predicate names the
	// table under test rather than a joined one. That is not cosmetic: the
	// previous form leaned on `JOIN users u`, and v143's social_providers
	// showed what happens when a tenant predicate is written against a joined
	// table and the join later moves — an org term in a LEFT JOIN's ON clause
	// filters nothing at all while still reading as scoped.
	conditions := fmt.Sprintf("bc.org_id = $%d", 1)
	args := []interface{}{org.ID}
	argIdx := 2

	if userID != "" {
		conditions += fmt.Sprintf(" AND bc.user_id::text = $%d", argIdx)
		args = append(args, userID)
		argIdx++
	}
	if status != "" {
		conditions += fmt.Sprintf(" AND bc.status = $%d", argIdx)
		args = append(args, status)
		argIdx++
	}
	if activeOnly {
		conditions += " AND bc.status = 'active' AND bc.valid_until > NOW() AND (bc.max_uses IS NULL OR bc.use_count < bc.max_uses)"
	}

	// Count total
	//orgscope:ignore org filter (bc.org_id) is applied via the interpolated conditions string, which the linter can't see
	var total int
	s.db.Pool.QueryRow(ctx, "SELECT COUNT(*) FROM mfa_bypass_codes bc WHERE "+conditions, args...).Scan(&total)

	// Get codes
	//orgscope:ignore org filter (bc.org_id) is applied via the interpolated conditions string, which the linter can't see
	query := fmt.Sprintf(`
		SELECT bc.id, bc.user_id, u.email, bc.reason, bc.generated_by, g.email,
			bc.valid_from, bc.valid_until, bc.max_uses, bc.use_count, bc.status,
			bc.used_at, bc.used_from_ip, bc.revoked_at, bc.revoked_by, bc.created_at
		FROM mfa_bypass_codes bc
		JOIN users u ON bc.user_id = u.id
		JOIN users g ON bc.generated_by = g.id
		WHERE %s
		ORDER BY bc.created_at DESC
		LIMIT $%d OFFSET $%d
	`, conditions, argIdx, argIdx+1)

	queryArgs := append(args, limit, offset)
	rows, err := s.db.Pool.Query(ctx, query, queryArgs...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var codes []MFABypassCode
	for rows.Next() {
		var c MFABypassCode
		// used_from_ip is nullable; scanning a NULL into a plain string fails and
		// would (previously) be silently swallowed by the continue below, so the
		// whole list came back empty even though total > 0. Scan nullable columns
		// into sql.Null* and project them onto the struct.
		var usedFromIP sql.NullString
		err := rows.Scan(
			&c.ID, &c.UserID, &c.UserEmail, &c.Reason, &c.GeneratedBy, &c.GeneratorEmail,
			&c.ValidFrom, &c.ValidUntil, &c.MaxUses, &c.UseCount, &c.Status,
			&c.UsedAt, &usedFromIP, &c.RevokedAt, &c.RevokedBy, &c.CreatedAt,
		)
		if err != nil {
			s.logger.Warn("ListBypassCodes: skipping row that failed to scan", zap.Error(err))
			continue
		}
		c.UsedFromIP = usedFromIP.String
		codes = append(codes, c)
	}
	if codes == nil {
		codes = []MFABypassCode{}
	}

	return codes, total, nil
}

// RevokeBypassCode revokes an active bypass code
func (s *Service) RevokeBypassCode(ctx context.Context, bypassID, adminID, ipAddress string) error {
	org, err := orgctx.From(ctx)
	if err != nil {
		return err
	}

	// The bare id here was a cross-tenant DENIAL, not a disclosure: an
	// administrator of one tenant could revoke another tenant's break-glass
	// code — the credential that exists precisely for the moment MFA is in the
	// way — and the owning tenant would discover it while locked out.
	var status, userID string
	err = s.db.Pool.QueryRow(ctx,
		"SELECT status, user_id FROM mfa_bypass_codes WHERE id = $1 AND org_id = $2",
		bypassID, org.ID,
	).Scan(&status, &userID)
	if err != nil {
		return errors.New("bypass code not found")
	}

	if status != "active" {
		return errors.New("bypass code is not active")
	}

	_, err = s.db.Pool.Exec(ctx,
		`UPDATE mfa_bypass_codes
		SET status = 'revoked', revoked_at = NOW(), revoked_by = $1
		WHERE id = $2 AND org_id = $3`,
		adminID, bypassID, org.ID,
	)
	if err != nil {
		return err
	}

	s.logBypassAudit(ctx, bypassID, userID, "revoked", &adminID, ipAddress, "", nil)

	return nil
}

// RevokeAllBypassCodes revokes all active codes for a user
func (s *Service) RevokeAllBypassCodes(ctx context.Context, userID, adminID, ipAddress string) (int, error) {
	org, err := orgctx.From(ctx)
	if err != nil {
		return 0, err
	}

	result, err := s.db.Pool.Exec(ctx,
		`UPDATE mfa_bypass_codes
		SET status = 'revoked', revoked_at = NOW(), revoked_by = $1
		WHERE user_id = $2 AND status = 'active' AND org_id = $3`,
		adminID, userID, org.ID,
	)
	if err != nil {
		return 0, err
	}

	count := int(result.RowsAffected())
	if count > 0 {
		s.logBypassAudit(ctx, "", userID, "revoked_all", &adminID, ipAddress, "", map[string]interface{}{
			"count": count,
		})
	}

	return count, nil
}

// GetBypassAuditLog returns audit log for bypass codes
func (s *Service) GetBypassAuditLog(ctx context.Context, userID string, limit, offset int) ([]MFABypassAuditEntry, error) {
	if limit <= 0 {
		limit = 100
	}

	org, err := orgctx.From(ctx)
	if err != nil {
		return nil, err
	}

	// The widest read in this file, and the console's own call site made it
	// wide: the user filter is optional, so `GET /mfa/bypass-codes/audit` with
	// no user returned every tenant's bypass history — who issued a code to
	// whom, when it was used, and from which address. An optional predicate is
	// not a predicate; the tenant term is the one that is never optional.
	query := `
		SELECT id, bypass_code_id, user_id, action, performed_by, ip_address, user_agent, details, created_at
		FROM mfa_bypass_audit
		WHERE org_id = $1 AND ($2 = '' OR user_id::text = $2)
		ORDER BY created_at DESC
		LIMIT $3 OFFSET $4
	`

	rows, err := s.db.Pool.Query(ctx, query, org.ID, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var entries []MFABypassAuditEntry
	for rows.Next() {
		var e MFABypassAuditEntry
		err := rows.Scan(&e.ID, &e.BypassCodeID, &e.UserID, &e.Action, &e.PerformedBy,
			&e.IPAddress, &e.UserAgent, &e.Details, &e.CreatedAt)
		if err != nil {
			continue
		}
		entries = append(entries, e)
	}

	return entries, nil
}

// ExpireOldBypassCodes marks expired codes.
//
// A maintenance sweep over the whole install, run from a scheduler with no
// tenant of its own. It only ever moves a code that has already passed its
// valid_until from 'active' to 'expired', so spanning organizations changes
// nothing an operator of one of them could observe or object to — and scoping
// it would mean either running it per organization for no benefit or leaving
// stale rows marked active in whichever tenant the scheduler happened to name.
func (s *Service) ExpireOldBypassCodes(ctx context.Context) (int, error) {
	result, err := s.db.Pool.Exec(orgctx.WithBypassRLS(ctx),
		//orgscope:ignore install-wide expiry sweep; only advances already-expired codes, deliberately spans tenants
		`UPDATE mfa_bypass_codes
		SET status = 'expired'
		WHERE status = 'active' AND valid_until < NOW()`,
	)
	if err != nil {
		return 0, err
	}
	return int(result.RowsAffected()), nil
}

// HasActiveBypassCode checks if user has an active bypass code.
//
// Called from the oauth service's MFA policy while deciding whether to demand a
// second factor, so it runs on the same may-have-no-org path as
// VerifyBypassCode and takes the same shape: belt lifted, tenant in the
// predicate. The direction of the failure matters here — an RLS-empty read
// answers "no bypass code", which makes the policy demand MFA rather than skip
// it, so this one fails safe. It is still wrong, and a control that is right by
// accident stops being right the first time somebody inverts the question.
func (s *Service) HasActiveBypassCode(ctx context.Context, userID string) (bool, error) {
	var count int
	//orgscope:ignore MFA-policy check on a path that may not have resolved an org; scoped by the user's own org_id
	err := s.db.Pool.QueryRow(orgctx.WithBypassRLS(ctx),
		`SELECT COUNT(*) FROM mfa_bypass_codes
		WHERE user_id = $1 AND status = 'active' AND valid_until > NOW()
		AND (max_uses IS NULL OR use_count < max_uses)
		AND org_id = (SELECT org_id FROM users WHERE id = $1)`,
		userID,
	).Scan(&count)
	return count > 0, err
}

// logBypassAudit records an audit entry
func (s *Service) logBypassAudit(ctx context.Context, bypassID, userID, action string, performedBy *string, ipAddress, userAgent string, details map[string]interface{}) {
	var bypassIDPtr *string
	if bypassID != "" {
		bypassIDPtr = &bypassID
	}
	var userIDPtr *string
	if userID != "" {
		userIDPtr = &userID
	}

	// The entry takes its tenant from the code it is about, then from the user,
	// then from the administrator who acted — narrowing the same way v145's
	// backfill does, so a row written now and a row filled in by the migration
	// agree. orgctx.AuditOrgID is the floor rather than the answer: this is
	// called from the bypassed verification path, where nothing on the
	// connection names a tenant, and a NULL org_id would be refused by the
	// belt's WITH CHECK and lost. Losing the record of an MFA bypass is the one
	// outcome worse than filing it under the wrong organization.
	fallback, resolved := orgctx.AuditOrgID(ctx)
	query := `
		INSERT INTO mfa_bypass_audit (id, org_id, bypass_code_id, user_id, action, performed_by, ip_address, user_agent, details, created_at)
		VALUES ($1,
		        COALESCE((SELECT org_id FROM mfa_bypass_codes WHERE id = $2),
		                 (SELECT org_id FROM users WHERE id = $3),
		                 (SELECT org_id FROM users WHERE id = $5),
		                 $9::uuid),
		        $2, $3, $4, $5, $6, $7, $8, NOW())
	`
	if _, err := s.db.Pool.Exec(orgctx.WithBypassRLS(ctx), query,
		uuid.New().String(), bypassIDPtr, userIDPtr, action, performedBy, ipAddress, userAgent, details, fallback); err != nil {
		// This used to discard the error, so a broken insert lost the record of
		// an MFA bypass without a trace anywhere.
		s.logger.Error("failed to write MFA bypass audit entry",
			zap.String("action", logsafe.Clean(action)),
			zap.String("user_id", logsafe.Clean(userID)),
			zap.Bool("org_resolved", resolved), zap.Error(err))
	}

	// Mirror into audit_events as well.
	//
	// mfa_bypass_audit is a private table: the unified audit trail, the
	// compliance reports and the SIEM forwarder all read audit_events, so a
	// bypass — issuing a code that skips the second factor, and using one — was
	// invisible to every one of them. It is the single most security-relevant
	// MFA event there is, and it was the one not being forwarded.
	actor := actorIDFromContext(ctx)
	if performedBy != nil && *performedBy != "" {
		actor = *performedBy
	}
	if ipAddress != "" {
		ctx = ContextWithActor(ctx, actor, ipAddress)
	}
	mirrored := map[string]interface{}{"bypass_action": action}
	for k, v := range details {
		mirrored[k] = v
	}
	if bypassID != "" {
		mirrored["bypass_code_id"] = bypassID
	}
	s.logAuditEvent(ctx, "identity", "mfa", "mfa.bypass_"+action, "success",
		actor, userID, "user", mirrored)
}
